// Modern AI engineering extensions: interoperable tools, agent reliability,
// inference efficiency, compiler thinking, and supply-chain discipline.
// These are intentionally dependency-free contracts so the learner can practice
// the mechanism in-browser before transferring it to a real runtime.

import { BuildEverythingProjectSchema, type BuildEverythingProject } from "../../schema/build-everything"

type ModernDraft = Omit<BuildEverythingProject, "steps" | "implementation">

function modern(draft: ModernDraft): BuildEverythingProject {
  return BuildEverythingProjectSchema.parse({
    ...draft,
    steps: [
      { id: `${draft.id}-derive`, number: 1, kind: "derive", title: "Derive the idea", prompt: draft.theory, deliverable: "State the system invariant in one sentence." },
      { id: `${draft.id}-build`, number: 2, kind: "build", title: "Build the smallest version", prompt: draft.build, deliverable: "Type the deterministic core." },
      { id: `${draft.id}-verify`, number: 3, kind: "verify", title: "Verify the invariant", prompt: draft.verify, deliverable: "Record a normal case and a boundary case." },
      { id: `${draft.id}-break`, number: 4, kind: "break", title: "Break one assumption", prompt: draft.experiment, deliverable: "Name the failure signal and its guard." },
      { id: `${draft.id}-ship`, number: 5, kind: "ship", title: "Package the artifact", prompt: draft.artifact, deliverable: "Save the contract, evidence, and handoff note." },
    ],
  })
}

const y = (
  order: number,
  code: string,
  id: string,
  title: string,
  lines: number,
  durationMinutes: number,
  coolFactor: string,
  sourceReuse: string,
  dependencies: string[],
  thinkingMove: string,
  theory: string,
  build: string,
  verify: string,
  experiment: string,
  artifact: string,
  externalDependencies: string[] = [],
) => modern({
  tier: "modern", order, code, id, title, lines, durationMinutes, coolFactor,
  sourcePage: 0, sourceReuse, dependencies, externalDependencies, thinkingMove,
  theory, build, verify, experiment, artifact,
})

export const buildEverythingModern: BuildEverythingProject[] = [
  y(50, "Y1", "y1-mcp-json-rpc", "MCP Server: JSON-RPC + Capability Negotiation", 70, 135, "Make tools discoverable without bespoke glue", "F3 + X9", ["f3-function-calling", "x9-safety-policy-gateway"], "negotiate before acting", "Modern AI integrations use a protocol boundary: initialize a session, negotiate capabilities, then exchange typed JSON-RPC messages.", "Validate request IDs, methods, protocol version, and advertised capabilities; return either a structured result or protocol error.", "Malformed JSON-RPC, unknown methods, and unsupported versions must never reach a tool implementation.", "Remove a capability, replay an old request, and send a notification with no ID.", "A protocol transcript with capability manifest and error taxonomy.", ["Model Context Protocol specification"]),
  y(51, "Y2", "y2-mcp-consent-audit", "MCP Tool Consent + Audit Log", 65, 120, "Make every external action reviewable", "Y1 + X9", ["y1-mcp-json-rpc", "x9-safety-policy-gateway"], "make authority explicit", "Tools, resources, and prompts have different control surfaces; sensitive tool calls require consent and an audit record.", "Authorize a tool call from an allowlist, require confirmation for sensitive actions, and append a redacted audit event.", "Denied calls produce no side effect, approved calls carry a stable actor/tool/request ID, and secrets never appear in the log.", "Try a sensitive action without consent, duplicate a request ID, and pass a secret-looking argument.", "A consent policy, append-only audit log, and replayable authorization trace.", ["Model Context Protocol tool safety"]),
  y(52, "Y3", "y3-agent-trace-evaluator", "Agent Trace Evaluator", 75, 150, "Score the whole agent run, not just the final text", "S4 + X7 + X8", ["s4-ai-coding-agent", "x7-inference-observability-trace", "x8-rag-evaluation"], "grade the trajectory", "Agent quality is an end-to-end property of tool choices, intermediate evidence, recovery, and final outcome; traces make those steps testable.", "Evaluate a trace against expected tools, maximum steps, required evidence, and a final outcome flag.", "The evaluator reports each violation, separates tool correctness from outcome success, and is deterministic.", "Insert a wrong tool, a redundant loop, missing evidence, and a successful final answer with an unsafe path.", "A trace-grade report with failure categories and a regression fixture.", ["Agent evaluation practice"]),
  y(53, "Y4", "y4-durable-agent-workflow", "Durable Agent Workflow + Idempotency", 70, 150, "Resume an interrupted agent without repeating side effects", "S4 + X6 + Y3", ["s4-ai-coding-agent", "x6-model-registry-canary", "y3-agent-trace-evaluator"], "separate intent from effects", "Long-running agents need checkpoints, retries, and idempotency keys so a crash does not duplicate an email, payment, or deploy.", "Apply events to a workflow state with a completed-key set; duplicate effects become no-ops and failed steps can resume.", "Replaying the same event twice yields the same state, unknown transitions are rejected, and checkpoints are serializable.", "Crash after the effect but before the checkpoint, retry a tool, and deliver events out of order.", "A durable workflow snapshot, idempotency ledger, and recovery transcript."),
  y(54, "Y5", "y5-structured-output-validator", "Structured Output + Schema Validation", 65, 120, "Turn model text into a safe typed value", "F3 + X3 + X9", ["f3-function-calling", "x3-evaluation-harness-calibration", "x9-safety-policy-gateway"], "reject ambiguity at the boundary", "Structured generation is only useful when untrusted output is parsed, validated, and repaired or rejected before application code sees it.", "Validate a JSON-like object against required fields, primitive types, enum values, and unknown-key policy.", "Valid objects pass unchanged, missing or mistyped fields return stable paths, and extra keys follow the declared policy.", "Add nested errors, null values, extra keys, and a coercion-looking string.", "A schema contract, validation error report, and safe fallback policy."),
  y(55, "Y6", "y6-capability-sandbox", "Capability Tokens + Tool Sandbox", 70, 135, "Give an agent exactly one permission at a time", "X9 + S4", ["x9-safety-policy-gateway", "s4-ai-coding-agent"], "minimize authority", "Capability security makes authority explicit: a tool receives a narrowly scoped token instead of ambient filesystem or network access.", "Issue and verify a token containing action, resource prefix, expiry, and nonce; reject mismatched or expired capabilities.", "A token cannot be widened, reused after expiry, or applied to a different resource prefix.", "Change the path prefix, advance the clock, replay a nonce, and request an unlisted action.", "A capability policy with denial reasons and a sandbox boundary diagram."),
  y(56, "Y7", "y7-prefix-cache-planner", "Prefix Cache Planner", 55, 105, "Reuse shared context without confusing tenants", "M4 + S1", ["m4-kv-cache", "s1-production-inference-server"], "share immutable prefixes", "Prefix caching saves prefill work only when requests share an exact, safe prefix; tenant and policy boundaries are part of the cache key.", "Group prompts by tenant and token prefix, compute shared-token savings, and never reuse a prefix across policy scopes.", "Identical prefixes share work, different scopes do not, and savings are computed from token counts rather than request counts.", "Change one token, tenant, or system policy and observe the cache miss.", "A prefix-cache plan with hit rate, saved tokens, and isolation evidence."),
  y(57, "Y8", "y8-paged-kv-allocator", "Paged KV-Cache Allocator", 75, 150, "Treat GPU memory like virtual memory", "M4 + M3", ["m4-kv-cache", "m3-flashattention"], "allocate blocks, not illusions", "Paged attention manages variable-length KV state with fixed blocks, free lists, and explicit fragmentation instead of one giant contiguous allocation.", "Allocate and free fixed-size blocks for requests, report logical-to-physical mappings, and reject capacity overflow.", "Freed blocks return to the pool, mappings preserve token order, and two requests never alias a live block.", "Free a middle request, allocate a longer request, and compare fragmentation against contiguous allocation.", "A KV page table, allocator trace, and memory-utilization report."),
  y(58, "Y9", "y9-speculative-decoding", "Speculative Decoding Acceptance", 65, 135, "Use a small draft model without changing target-model answers", "E2 + M4", ["e2-generate-text", "m4-kv-cache"], "verify before committing", "Speculative decoding drafts several tokens cheaply, then accepts the longest target-agreeing prefix and falls back to the target token at the first mismatch.", "Compare draft and target token sequences and return accepted prefix length plus the emitted target token.", "The emitted sequence preserves target semantics, empty drafts are valid, and a mismatch stops acceptance at the first position.", "Vary draft length, put the mismatch at the beginning or end, and measure accepted-token ratio.", "An acceptance trace with speedup assumptions and correctness evidence."),
  y(59, "Y10", "y10-quantization-calibration", "Quantization Calibration + Error Budget", 70, 135, "Trade bits for memory with a measured error budget", "D1 + S1", ["d1-triton-relu-kernel", "s1-production-inference-server"], "measure compression error", "Quantization maps a real range to finite integer levels; calibration data chooses the range and the error budget decides whether the result is safe.", "Calibrate a symmetric scale, quantize and dequantize values, and report max absolute error and bytes saved.", "Zero values stay near zero, the quantized range is bounded, and the report exposes the chosen scale and error.", "Add an outlier, change bit width, and compare percentile clipping with min/max calibration.", "A quantization card with calibration set, scale, error budget, and quality decision."),
  y(60, "Y11", "y11-graph-capture-cache", "Graph Capture + Compile Cache", 65, 120, "Know when compilation helps—and when shapes break it", "C4 + D1", ["c4-transformer-block", "d1-triton-relu-kernel"], "separate graph from values", "Modern compilers capture a stable computation graph and cache compiled variants; dynamic shapes can trigger recompilation or graph breaks.", "Build a deterministic cache key from operation graph and input shapes, report hits/misses, and flag unsupported dynamic shapes.", "Equivalent graphs and shapes share a key; one changed shape or operation creates a new compilation artifact.", "Toggle dynamic dimensions, insert a graph break, and compare compile overhead with steady-state runs.", "A compile cache manifest with graph hash, shape policy, and warmup report.", ["PyTorch torch.compile and TorchInductor"]),
  y(61, "Y12", "y12-model-supply-chain-signing", "Model Supply Chain + Artifact Signing", 70, 135, "Refuse a model that cannot prove where it came from", "E1 + S6", ["e1-load-huggingface-model", "s6-distributed-trainer"], "verify before loading", "A model artifact needs provenance: digest, source, license, datasets, signer, and verification status before deployment.", "Create and verify a manifest digest against an approved signature and required provenance fields.", "Tampering, missing provenance, expired signatures, and unapproved signers must fail closed.", "Change one byte, signer, dataset, or expiry and inspect the exact rejection reason.", "A signed model card, provenance manifest, and verification transcript.", ["OpenSSF Model Signing"]),
  y(62, "Y13", "y13-mlperf-style-benchmark", "MLPerf-Style Inference Benchmark", 75, 150, "Compare systems fairly instead of chasing one lucky latency", "S1 + X7", ["s1-production-inference-server", "x7-inference-observability-trace"], "benchmark the workload", "A credible benchmark fixes workload, quality target, latency percentile, throughput, and warmup rules so optimizations remain comparable.", "Summarize timed request runs into throughput, p95 latency, quality pass rate, warmup exclusion, and an SLO verdict.", "Warmup runs cannot inflate results, p95 is deterministic, and a quality failure blocks a performance win.", "Change concurrency, add a slow tail, and lower quality while increasing throughput.", "A reproducible benchmark report with workload manifest and SLO decision.", ["MLCommons MLPerf Inference"]),
  y(63, "Y14", "y14-streaming-backpressure", "Streaming Responses + Backpressure", 65, 120, "Keep a live stream responsive under a slow client", "S1 + X7 + M4", ["s1-production-inference-server", "x7-inference-observability-trace", "m4-kv-cache"], "bound in-flight work", "Streaming systems need bounded buffers, cancellation, and backpressure; otherwise one slow consumer turns token generation into an outage.", "Simulate producer chunks and consumer capacity, returning delivered chunks, dropped or cancelled work, and peak buffer depth.", "The buffer never exceeds capacity, cancellation stops future delivery, and every dropped chunk has a reason.", "Slow the consumer, cancel mid-stream, and compare bounded versus unbounded buffering.", "A streaming trace with buffer SLO, cancellation evidence, and recovery policy."),
]
