// Draft level banks for future engine work. Dedicated routes are required before
// an engine becomes playable; unfinished engines must not use this generic UI.

export type PatternGameLevel = {
  prompt: string
  instruction: string
  options: { label: string; value: string }[]
  correct: string
  success: string
  miss: string
  visual: "repair" | "frontier" | "garden" | "state" | "compress" | "proof"
}

export const PATTERN_GAME_LEVELS: Record<string, PatternGameLevel[]> = {
  "invariant-inspector": [
    { visual: "repair", prompt: "A sorted structure is being updated. Which move protects its rule?", instruction: "Tap the safe operation.", options: [{ label: "Insert the value where both sides stay ordered", value: "safe" }, { label: "Put it at the root and sort later", value: "root" }, { label: "Ignore order until the final query", value: "ignore" }], correct: "safe", success: "The invariant survives the operation.", miss: "The structure may look fine locally, but the global rule is broken." },
    { visual: "repair", prompt: "A node violates the range inherited from its ancestors. What do you inspect?", instruction: "Find the first broken constraint.", options: [{ label: "The full legal range carried down to this node", value: "range" }, { label: "Only the node's immediate children", value: "children" }, { label: "The color of the node", value: "color" }], correct: "range", success: "Constraints flow downward from the whole path.", miss: "A local check can miss a violation imposed by a distant ancestor." },
    { visual: "repair", prompt: "A pointer update is about to lose the rest of a list. What must happen first?", instruction: "Protect the next link.", options: [{ label: "Save next before changing current.next", value: "save" }, { label: "Move current twice", value: "twice" }, { label: "Copy the whole list every time", value: "copy" }], correct: "save", success: "Pointer surgery starts by preserving the path ahead.", miss: "Once the only arrow forward is overwritten, the remaining structure is unreachable." },
  ],
  "frontier-runner": [
    { visual: "frontier", prompt: "Three nodes are one, two, and three steps away. Which should the frontier visit first?", instruction: "Move the frontier to the nearest layer.", options: [{ label: "The node one edge away", value: "near" }, { label: "The node with the largest label", value: "label" }, { label: "Any node; order cannot matter", value: "any" }], correct: "near", success: "Layer order gives the shortest unweighted path.", miss: "A frontier only carries a guarantee when its order means something." },
    { visual: "frontier", prompt: "An edge costs 1. Another costs 8. Which frontier should Dijkstra settle?", instruction: "Choose the cheapest unsettled path.", options: [{ label: "The frontier with the smallest total cost", value: "cheap" }, { label: "The frontier discovered first", value: "first" }, { label: "The frontier with the most outgoing edges", value: "wide" }], correct: "cheap", success: "The cheapest unsettled frontier is safe to settle.", miss: "Discovery order is not cost order once edges have weights." },
    { visual: "frontier", prompt: "A relaxation finds a cheaper route to a node already on the frontier. What do you do?", instruction: "Let the better evidence move the boundary.", options: [{ label: "Replace its distance and reprioritize it", value: "update" }, { label: "Keep the first distance forever", value: "keep" }, { label: "Delete the node", value: "delete" }], correct: "update", success: "Relaxation keeps the best known frontier alive.", miss: "A frontier is a belief about the best route so far, not a permanent fact." },
  ],
  "decision-garden": [
    { visual: "garden", prompt: "You are building every valid combination. What is each level of the decision tree?", instruction: "Plant the next decision.", options: [{ label: "One choice for the next item", value: "choice" }, { label: "A random result", value: "random" }, { label: "The final answer immediately", value: "answer" }], correct: "choice", success: "Each level represents one decision in the search space.", miss: "A decision tree is useful only when its levels have a stable meaning." },
    { visual: "garden", prompt: "You chose an item, explored it, and now need to try its sibling. What must happen?", instruction: "Restore the shared path.", options: [{ label: "Unchoose and restore the state", value: "undo" }, { label: "Keep the old choice in the path", value: "keep" }, { label: "Restart the entire tree", value: "restart" }], correct: "undo", success: "Choose–explore–unchoose lets branches share one path.", miss: "Without restoration, one branch contaminates the next." },
    { visual: "garden", prompt: "A branch already exceeds the target. What makes pruning legitimate?", instruction: "Cut only what you can prove.", options: [{ label: "The branch can no longer satisfy the constraint", value: "proof" }, { label: "The branch looks less promising", value: "looks" }, { label: "The branch is taking too long", value: "slow" }], correct: "proof", success: "Pruning is a proof that the branch cannot recover.", miss: "Speed alone is not evidence that a branch is impossible." },
  ],
  "state-forge": [
    { visual: "state", prompt: "You are standing at step i with amnesia. What must your state remember?", instruction: "Keep only what changes the future answer.", options: [{ label: "The smallest information that determines the remaining answer", value: "minimal" }, { label: "The entire history", value: "all" }, { label: "Only the final answer", value: "final" }], correct: "minimal", success: "State is the smallest memory that preserves the future.", miss: "Remembering everything creates noise; forgetting a necessary variable breaks the recurrence." },
    { visual: "state", prompt: "Two recursive calls ask the exact same state. What should the table do?", instruction: "Turn repeated work into memory.", options: [{ label: "Reuse the stored answer", value: "reuse" }, { label: "Compute it again for purity", value: "again" }, { label: "Delete both calls", value: "delete" }], correct: "reuse", success: "Overlap becomes memoization when the state key is stable.", miss: "The repeated state is the signal that the call tree hides a graph." },
    { visual: "state", prompt: "A table cell depends on the previous row and left neighbor. What is the fill order?", instruction: "Follow dependency arrows.", options: [{ label: "Fill only after every dependency is ready", value: "deps" }, { label: "Fill cells in random order", value: "random" }, { label: "Fill the final cell first", value: "final" }], correct: "deps", success: "Tabulation is a dependency order made visible.", miss: "A table is not a picture to fill; it is a graph of dependencies." },
  ],
  "compression-workshop": [
    { visual: "compress", prompt: "You need many prefix queries over the same words. What should remember shared beginnings?", instruction: "Choose the structure that stores overlap once.", options: [{ label: "A trie", value: "trie" }, { label: "A fresh scan per query", value: "scan" }, { label: "A random tree", value: "random" }], correct: "trie", success: "The structure compresses shared prefixes into one path.", miss: "Repeated scanning pays for the same prefix over and over." },
    { visual: "compress", prompt: "You repeatedly need the largest urgent item. What should sit at the top?", instruction: "Keep the useful extreme accessible.", options: [{ label: "A heap root", value: "heap" }, { label: "The oldest item", value: "oldest" }, { label: "Every item sorted after each query", value: "sort" }], correct: "heap", success: "A local heap rule exposes a global extreme.", miss: "Sorting everything spends work on order you never query." },
    { visual: "compress", prompt: "A bitmask represents which items are selected. What does one bit encode?", instruction: "Read the mask as membership.", options: [{ label: "Whether one item belongs to the set", value: "member" }, { label: "The item's full value", value: "value" }, { label: "The order of every item", value: "order" }], correct: "member", success: "Bits become compact membership flags.", miss: "A mask stores a yes/no decision per position, not the whole object." },
  ],
  "proof-arena": [
    { visual: "proof", prompt: "You propose a greedy choice. What would make it trustworthy?", instruction: "Challenge the shortcut.", options: [{ label: "An exchange argument shows an optimum can adopt it", value: "exchange" }, { label: "It works on one example", value: "example" }, { label: "It feels locally best", value: "feel" }], correct: "exchange", success: "A safe shortcut needs a reason it never destroys optimality.", miss: "One successful example cannot prove a greedy choice." },
    { visual: "proof", prompt: "Two values share a common divisor. Which reduction preserves the answer?", instruction: "Keep the invariant through the reduction.", options: [{ label: "Replace (a,b) with (b, a mod b)", value: "gcd" }, { label: "Subtract a random number", value: "random" }, { label: "Try every pair forever", value: "all" }], correct: "gcd", success: "Euclid preserves the common divisors while shrinking the problem.", miss: "A reduction is useful only when the answer survives the transformation." },
    { visual: "proof", prompt: "You need x¹⁶. Why is repeated squaring a better route?", instruction: "Halve the remaining work.", options: [{ label: "x¹⁶ = (x⁸)² = ((x⁴)²)²", value: "square" }, { label: "Multiply x sixteen separate times", value: "repeat" }, { label: "Guess the answer from x", value: "guess" }], correct: "square", success: "Squaring reuses a solved half and turns the chain logarithmic.", miss: "The shortcut must expose how much work it removes, not merely look shorter." },
  ],
}
