// ai-ml question bank — Track: Data engineering and classical baselines (docs/13).
// DATA-001 … BASE-005.

import { q } from "./questions-math"
import type { AiQuestion } from "../../../schema/question"

export const dataQuestions: AiQuestion[] = [
  q({
    id: "DATA-001", track: "data", lessonId: "ai-ml/00-data-contract/what-counts-as-training-data",
    kind: "construction",
    prompt: "Choose the required fields for this document contract: tickets with text, label, author, and optional attachments.",
    contextFixture: { fields: ["id", "text", "label", "author", "attachment"] },
    expectedArtifact: "id, text, label are required; author/attachment are optional — the model only consumes id, text, label.",
    rubric: ["Requires id, text, label", "Marks author/attachment optional", "Justifies by what the model consumes"],
    hints: ["Which fields does the model actually read?", "What happens if label is missing?", "Required = needed to train, not nice to have."],
    pattern: "Dataset contract",
    prerequisites: [],
    nextQuestionId: "DATA-002",
  }),
  q({
    id: "DATA-002", track: "data", lessonId: "ai-ml/00-data-contract/what-counts-as-training-data",
    kind: "prediction",
    prompt: "Two rows share identical text and label. Which duplicate survives under first-occurrence-wins, and why does that rule matter?",
    contextFixture: { first: "r05", second: "r23", rule: "first-occurrence-wins" },
    expectedTraceObservation: "r05 survives, r23 is rejected: order is deterministic, so the rule is reproducible and unbiased by file order changes.",
    rubric: ["Picks the first occurrence", "States the determinism benefit", "States duplicates double-count if kept"],
    hints: ["Which row is encountered first in a stable file?", "What if the rule depended on sorting?", "Keeping both doubles a row's weight silently."],
    pattern: "Duplicate policy",
    prerequisites: ["DATA-001"],
    nextQuestionId: "DATA-003",
  }),
  q({
    id: "DATA-003", track: "data", lessonId: "ai-ml/00-data-contract/what-counts-as-training-data",
    kind: "debugging",
    prompt: "A row has text: 12345 (a number). Repair this malformed record WITHOUT hiding the error.",
    contextFixture: { row: { id: "r28", text: 12345, label: "question" } },
    expectedArtifact: "Cast or quote to a string — and record the repair in the lineage; never silently coerce and forget.",
    rubric: ["Fixes the type", "Keeps a repair record", "Rejects silent coercion"],
    hints: ["What is the right type for text?", "Should the fix be invisible in the log?", "A repair without a record is a hidden lie."],
    pattern: "Data repair",
    prerequisites: ["DATA-001"],
    nextQuestionId: "DATA-004",
  }),
  q({
    id: "DATA-004", track: "data", lessonId: "ai-ml/00-data-contract/what-counts-as-training-data",
    kind: "comparison",
    prompt: "Separate these three values: a missing label (absent), an unknown label ('unknown'), and an invalid label ('xqzz'). Which belongs in training?",
    contextFixture: { missing: "absent", unknown: "'unknown'", invalid: "'xqzz'" },
    expectedArtifact: "None trains as a real label: missing → reject; unknown → reject or map deliberately; invalid → reject with its own reason.",
    rubric: ["Treats the three differently", "Rejects invalid values", "Names a policy per case"],
    hints: ["Can the model learn from an absent answer?", "Is 'unknown' a class you defined?", "Invalid values must not silently become a class."],
    pattern: "Missing vs invalid",
    prerequisites: ["DATA-001"],
    nextQuestionId: "DATA-005",
  }),
  q({
    id: "DATA-005", track: "data", lessonId: "ai-ml/00-data-contract/what-counts-as-training-data",
    kind: "implementation",
    prompt: "Write the rejection reason for a leaked label: a row already used in the held-out set. Make the reason distinct from all other rejections.",
    contextFixture: { inEval: true, reasons: ["duplicate", "missing-label", "malformed"] },
    expectedArtifact: "reason = 'reserved' (or 'leaked'): a dedicated category, so leak counts are queryable later.",
    rubric: ["Uses a distinct reason string", "Explains why distinctness matters", "Maps it to the in_eval flag"],
    hints: ["Why must 'duplicate' not swallow this row?", "What flag marks the row?", "A queryable category makes leaks auditable."],
    pattern: "Rejection taxonomy",
    prerequisites: ["DATA-002"],
    nextQuestionId: "DATA-006",
  }),
  q({
    id: "DATA-006", track: "data", lessonId: "ai-ml/00-data-contract/split-the-evidence",
    kind: "prediction",
    prompt: "Predict the result of this temporal split: tickets sorted by creation date, first 80% train, last 20% test. What risks does it carry?",
    contextFixture: { order: "creation time", train: 80, test: 20 },
    expectedTraceObservation: "Clean of future leakage, but if ticket style shifts over time, train and test come from different distributions.",
    rubric: ["Sees the no-leakage benefit", "Names the drift risk", "States when temporal split is right"],
    hints: ["Can the model ever see the future in this split?", "Do older and newer tickets look identical?", "Temporal split trades leakage for drift."],
    pattern: "Temporal split",
    prerequisites: ["THEORY-006"],
    nextQuestionId: "DATA-007",
  }),
  q({
    id: "DATA-007", track: "data", lessonId: "ai-ml/00-data-contract/split-the-evidence",
    kind: "debugging",
    prompt: "Author 'chen' appears in both train and test. Find the group that leaks and state the harm.",
    contextFixture: { groups: ["ana", "brian", "chen", "dana"], leaked: "chen" },
    expectedArtifact: "chen's style is memorized, not generalized: the test set overestimates skill on unseen authors.",
    rubric: ["Names the group", "Explains the memorization harm", "Proposes group-wise split"],
    hints: ["What do chen's rows share beyond the label?", "What can the model copy instead of learn?", "Split by author, not by row."],
    pattern: "Group leakage",
    prerequisites: ["THEORY-006"],
    nextQuestionId: "DATA-008",
  }),
  q({
    id: "DATA-008", track: "data", lessonId: "ai-ml/03-experiments/reproducibility-is-part-of-correctness",
    kind: "construction",
    prompt: "Design a dataset version identifier: the same source rows cleaned twice must produce the same id, and a changed row must produce a different one.",
    contextFixture: { requirement: "content-addressed" },
    expectedArtifact: "A hash over the canonical row set (ids + text + labels + policy version), e.g. sha256; metadata changes bump the id.",
    rubric: ["Hashes content, not timestamp", "Includes policy version", "States collision/replay safety"],
    hints: ["What should NOT change the id — a re-run?", "Which fields must the hash include?", "A content hash makes rebuilds checkable."],
    pattern: "Version identity",
    prerequisites: ["DATA-001"],
    nextQuestionId: "DATA-009",
  }),
  q({
    id: "DATA-009", track: "data", lessonId: "ai-ml/03-experiments/reproducibility-is-part-of-correctness",
    kind: "operations",
    prompt: "An ingestion job failed after row 400 of 1,000. Recover it from its checkpoint without reprocessing the first 400 rows.",
    contextFixture: { processed: 400, total: 1000, checkpoint: "row 400 committed" },
    expectedArtifact: "Resume at row 401 using the committed checkpoint; the job must be idempotent so re-processing row 400 is harmless.",
    rubric: ["Resumes from the checkpoint", "Does not reprocess committed rows", "Uses idempotent writes"],
    hints: ["What was already committed?", "What is the smallest safe restart point?", "What if the failure was mid-row?"],
    pattern: "Checkpointing",
    prerequisites: ["DATA-008"],
    nextQuestionId: "DATA-010",
  }),
  q({
    id: "DATA-010", track: "data", lessonId: "ai-ml/04-inference-service/serve-the-model-safely",
    kind: "prediction",
    prompt: "A retry resends the same ingestion batch after a timeout. Is this retry idempotent? Decide and justify.",
    contextFixture: { retry: "same batch", prior: "may have committed" },
    expectedArtifact: "Not idempotent as written: the second send duplicates rows unless a batch id makes the commit a no-op.",
    rubric: ["Says not idempotent", "Names the duplicate risk", "Adds the batch-id fix"],
    hints: ["Could the first attempt have succeeded?", "What happens when both attempts commit?", "A unique batch id turns the second commit into a no-op."],
    pattern: "Idempotency",
    prerequisites: ["DATA-009"],
    nextQuestionId: "BASE-001",
  }),
  q({
    id: "BASE-001", track: "data", lessonId: "ai-ml/01-baseline/the-baseline-earns-the-right-to-improve",
    kind: "implementation",
    prompt: "Build a majority-class baseline for these labels: 90 question, 6 bug, 4 feature. What does it predict for every row, and what is its accuracy?",
    contextFixture: { question: 90, bug: 6, feature: 4 },
    expectedArtifact: "Predict 'question' always; accuracy 90%; recall 0 for bug and feature.",
    rubric: ["Picks the majority label", "Computes accuracy", "Reports the zero recalls"],
    hints: ["Which class is the majority?", "How often is that guess right?", "What is the recall on the other two classes?"],
    pattern: "Majority baseline",
    prerequisites: [],
    nextQuestionId: "BASE-002",
  }),
  q({
    id: "BASE-002", track: "data", lessonId: "ai-ml/01-baseline/the-baseline-earns-the-right-to-improve",
    kind: "construction",
    prompt: "Build a keyword baseline for bug detection: flag rows containing 'crash', 'error', or 'broken'. State its blind spot.",
    contextFixture: { keywords: ["crash", "error", "broken"] },
    expectedArtifact: "Flags keyword rows; blind spot: bugs described without those words (e.g. 'dashboard shows 0').",
    rubric: ["Builds the keyword rule", "Names a miss case", "States precision/recall tradeoff"],
    hints: ["What does the rule catch reliably?", "Can a bug avoid all three keywords?", "High recall usually costs precision, or vice versa."],
    pattern: "Keyword baseline",
    prerequisites: ["BASE-001"],
    nextQuestionId: "BASE-003",
  }),
  q({
    id: "BASE-003", track: "data", lessonId: "ai-ml/04-retrieval/ranking-is-a-separate-responsibility",
    kind: "prediction",
    prompt: "For a ranking problem (best ticket answers first), choose a baseline and predict how it performs: popularity, recency, or random.",
    contextFixture: { task: "rank answers", options: ["popularity", "recency", "random"] },
    expectedArtifact: "Popularity is the honest baseline: it captures prior relevance with zero learning and is easy to beat meaningfully.",
    rubric: ["Picks a defensible baseline", "Explains why random is too weak", "States popularity's bias"],
    hints: ["Which baseline encodes any signal at all?", "What can random never tell you?", "Popularity over-rewards old content — note it."],
    pattern: "Baseline choice",
    prerequisites: ["BASE-001"],
    nextQuestionId: "BASE-004",
  }),
  q({
    id: "BASE-004", track: "data", lessonId: "ai-ml/03-experiments/build-a-better-baseline-honestly",
    kind: "comparison",
    prompt: "Compare this model and baseline: model 0.91, baseline 0.90, same split. Is this improvement meaningful?",
    contextFixture: { model: 0.91, baseline: 0.90, split: "same" },
    expectedArtifact: "Suspicious: +0.01 on the same split is within noise; require a fixed split, error analysis, and significance before believing it.",
    rubric: ["Sees the split is held fixed", "Questions the small delta", "Demands error analysis"],
    hints: ["Was the split identical?", "Can +0.01 come from luck?", "What would make the improvement credible?"],
    pattern: "Honest comparison",
    prerequisites: ["BASE-003"],
    nextQuestionId: "BASE-005",
  }),
  q({
    id: "BASE-005", track: "data", lessonId: "ai-ml/01-baseline/the-baseline-earns-the-right-to-improve",
    kind: "communication",
    prompt: "A random baseline gets 0.5 AUC. Explain to a teammate why this random baseline is still useful, not useless.",
    contextFixture: { randomAUC: 0.5, modelAUC: 0.61 },
    expectedArtifact: "Random defines the floor: 0.5 AUC means 'no skill' — every real system must beat it and show HOW, so the random line makes the improvement legible.",
    rubric: ["States the floor role", "Names what must beat it", "Explains legibility of the delta"],
    hints: ["What does 0.5 mean in ranking terms?", "What can you prove by beating it?", "A comparison needs a zero point."],
    pattern: "Baseline honesty",
    prerequisites: ["BASE-003"],
    nextQuestionId: "MODEL-001",
  }),
]
