// ai-ml question bank — Track: Retrieval, ranking, and recommendation (docs/13).
// SEARCH-001 … REC-005.

import { q } from "./questions-math"
import type { AiQuestion } from "../../../schema/question"

export const retrievalQuestions: AiQuestion[] = [
  q({
    id: "SEARCH-001", track: "retrieval", lessonId: "ai-ml/06-retrieval/search-before-generation",
    kind: "implementation",
    prompt: "Build an inverted index for these five documents: map each term to the documents containing it.",
    contextFixture: { docs: ["the cat ran", "the dog ran", "cat food", "dog food", "ran home"] },
    expectedArtifact: "term → doc list: 'cat'→[0,2], 'dog'→[1,3], 'ran'→[0,1,4], 'food'→[2,3], etc. — posting lists, not re-scans.",
    rubric: ["Indexes every term", "Maps to document sets", "Avoids full scans"],
    hints: ["For one term, which docs contain it?", "Do this for every unique term.", "The index trades build cost for query speed."],
    pattern: "Inverted index",
    prerequisites: [],
    nextQuestionId: "SEARCH-002",
  }),
  q({
    id: "SEARCH-002", track: "retrieval", lessonId: "ai-ml/06-retrieval/search-before-generation",
    kind: "derivation",
    prompt: "Calculate term frequency and inverse document frequency for 'crash' in 3 of 10 documents.",
    contextFixture: { tf: 2, df: 3, n: 10 },
    expectedArtifact: "tf = 2; idf = log(10/3) ≈ 1.20 — common terms get damped, rare terms get weight.",
    rubric: ["Computes tf", "Computes idf", "Explains the damping"],
    hints: ["What is tf here?", "idf = log(N/df).", "Why damp a term in half the docs?"],
    pattern: "TF-IDF",
    prerequisites: ["SEARCH-001"],
    nextQuestionId: "SEARCH-003",
  }),
  q({
    id: "SEARCH-003", track: "retrieval", lessonId: "ai-ml/06-retrieval/search-before-generation",
    kind: "implementation",
    prompt: "Rank these documents with BM25-style evidence for the query 'crash fix': score = sum of idf × tf-weight over matching terms.",
    contextFixture: { query: ["crash", "fix"], docs: { a: "crash crash", b: "fix release", c: "crash fix guide" } },
    expectedArtifact: "c scores highest (both terms), then a (crash twice, no fix), then b — matching more query terms ranks first.",
    rubric: ["Scores each doc", "Rewards term overlap", "Orders by total"],
    hints: ["Which doc matches both terms?", "Does repetition count?", "Sum over matching query terms."],
    pattern: "Lexical ranking",
    prerequisites: ["SEARCH-002"],
    nextQuestionId: "SEARCH-004",
  }),
  q({
    id: "SEARCH-004", track: "retrieval", lessonId: "ai-ml/06-retrieval/search-before-generation",
    kind: "debugging",
    prompt: "Diagnose this lexical retrieval miss: the query 'dashboard shows zero' returns nothing, but a ticket about 'revenue display bug' should match.",
    contextFixture: { query: "dashboard shows zero", relevant: "revenue display bug", issue: "no shared tokens" },
    expectedArtifact: "Vocabulary mismatch: zero lexical overlap; the fix is synonyms, expansion, or semantic retrieval — the index is not wrong, the representation is.",
    rubric: ["Names the mismatch", "Distinguishes index from representation", "Prescribes expansion/semantics"],
    hints: ["Which words do the two share?", "Is the index broken or the representation?", "What bridges different words?"],
    pattern: "Vocabulary mismatch",
    prerequisites: ["SEARCH-003"],
    nextQuestionId: "SEARCH-005",
  }),
  q({
    id: "SEARCH-005", track: "retrieval", lessonId: "ai-ml/06-retrieval/search-before-generation",
    kind: "construction",
    prompt: "Design a retrieval evaluation set: 20 queries, relevant documents per query, and the metric to report.",
    contextFixture: { queries: 20, relevance: "per query", metric: "recall@5" },
    expectedArtifact: "Label relevance per (query, doc), compute recall@5 and MRR over the labeled set — judgments, not vibes, and a fixed split.",
    rubric: ["Defines relevance labels", "Picks retrieval metrics", "Freezes the evaluation set"],
    hints: ["What counts as a good result for a query?", "Which metric checks the top few?", "Judgments must be frozen."],
    pattern: "Retrieval eval",
    prerequisites: ["SEARCH-003"],
    nextQuestionId: "VECTOR-001",
  }),
  q({
    id: "VECTOR-001", track: "retrieval", lessonId: "ai-ml/06-retrieval/similarity-is-a-representation-choice",
    kind: "derivation",
    prompt: "Calculate nearest-neighbor similarity: doc A [1, 0, 0], doc B [0.8, 0.2, 0], query [1, 0, 0.1]. Which doc is closer, by cosine?",
    contextFixture: { a: [1, 0, 0], b: [0.8, 0.2, 0], q: [1, 0, 0.1] },
    expectedArtifact: "cos(q,a) ≈ 0.995 vs cos(q,b) ≈ 0.992 — a is marginally closer; direction, not magnitude, decides.",
    rubric: ["Computes both cosines", "Compares direction", "States cosine's magnitude blindness"],
    hints: ["Compute q·a and |q||a|.", "Do the same for b.", "Which angle is smaller?"],
    pattern: "Cosine similarity",
    prerequisites: ["MATH-003"],
    nextQuestionId: "VECTOR-002",
  }),
  q({
    id: "VECTOR-002", track: "retrieval", lessonId: "ai-ml/06-retrieval/similarity-is-a-representation-choice",
    kind: "debugging",
    prompt: "Diagnose this embedding-space collision: 'refund policy' and 'refund denied' map to nearly identical vectors and rank together.",
    contextFixture: { a: "refund policy", b: "refund denied", distance: "tiny" },
    expectedArtifact: "The encoder collapsed the distinction (or the vectors over-weight the shared prefix); fine-tune or re-encode with a better-trained model.",
    rubric: ["Names the collapse", "Notes shared-prefix dominance", "Prescribes a better encoder"],
    hints: ["What do the two texts share?", "Which model produced the vectors?", "Retraining changes the space."],
    pattern: "Embedding collision",
    prerequisites: ["VECTOR-001"],
    nextQuestionId: "VECTOR-003",
  }),
  q({
    id: "VECTOR-003", track: "retrieval", lessonId: "ai-ml/06-retrieval/similarity-is-a-representation-choice",
    kind: "prediction",
    prompt: "Choose an index for latency versus freshness: 10M vectors, updates every minute, p99 under 50 ms.",
    contextFixture: { vectors: "10M", updates: "1/min", p99: "50ms" },
    expectedArtifact: "An approximate index (HNSW/IVF) for the latency, with a freshness policy — rebuild or incremental index so updates land within a minute.",
    rubric: ["Picks approximate index", "States the latency reason", "Adds a freshness policy"],
    hints: ["Can exact scan hit 50 ms at 10M?", "What trades a little recall for speed?", "When do new vectors become searchable?"],
    pattern: "Index choice",
    prerequisites: ["VECTOR-001"],
    nextQuestionId: "VECTOR-004",
  }),
  q({
    id: "VECTOR-004", track: "retrieval", lessonId: "ai-ml/06-retrieval/similarity-is-a-representation-choice",
    kind: "debugging",
    prompt: "Detect stale vectors after these document updates: 40 docs were edited, but search still returns the old versions.",
    contextFixture: { edits: 40, symptom: "old versions returned" },
    expectedArtifact: "The index wasn't rebuilt on edit (write-through missing); add an update hook that re-embeds and replaces the stale vectors.",
    rubric: ["Names the stale index", "Finds the missing hook", "Prescribes re-embed on edit"],
    hints: ["Where do edits flow?", "What re-embeds the changed docs?", "The index must hear about updates."],
    pattern: "Index freshness",
    prerequisites: ["VECTOR-003"],
    nextQuestionId: "VECTOR-005",
  }),
  q({
    id: "VECTOR-005", track: "retrieval", lessonId: "ai-ml/06-retrieval/similarity-is-a-representation-choice",
    kind: "comparison",
    prompt: "Compare lexical and semantic retrieval for this query: 'app crashed' vs 'application terminated unexpectedly'.",
    contextFixture: { query: "app crashed", semantic: "application terminated unexpectedly" },
    expectedArtifact: "Lexical misses (no shared tokens); semantic matches — but lexical wins on exact keywords; the two complement, so hybrid.",
    rubric: ["Shows lexical miss", "Shows semantic match", "Recommends hybrid"],
    hints: ["What do the texts share literally?", "What captures meaning?", "Which is safer for exact terms?"],
    pattern: "Lexical vs semantic",
    prerequisites: ["SEARCH-004"],
    nextQuestionId: "RANK-001",
  }),
  q({
    id: "RANK-001", track: "retrieval", lessonId: "ai-ml/06-retrieval/ranking-is-a-separate-responsibility",
    kind: "construction",
    prompt: "Separate candidate recall from final ranking: 50 candidates come from retrieval, 10 must reach the user. Design the two stages.",
    contextFixture: { candidates: 50, shown: 10 },
    expectedArtifact: "Stage 1 recall keeps the 50 cheap; Stage 2 reranks with richer features to pick the 10 — each stage optimizes its own objective.",
    rubric: ["Separates the two stages", "Assigns a cheap stage", "Assigns a rich stage"],
    hints: ["What must be cheap?", "What can afford to be expensive?", "Each stage has its own goal."],
    pattern: "Recall vs rank",
    prerequisites: ["SEARCH-005"],
    nextQuestionId: "RANK-002",
  }),
  q({
    id: "RANK-002", track: "retrieval", lessonId: "ai-ml/06-retrieval/ranking-is-a-separate-responsibility",
    kind: "construction",
    prompt: "Choose ranking features for this query: a user searching 'bug' in tickets. Pick three features that should order the results.",
    contextFixture: { query: "bug", features: ["keyword match", "recency", "author rank", "length"] },
    expectedArtifact: "keyword match, recency, and author rank — each adds evidence; length adds noise and should not order results.",
    rubric: ["Picks informative features", "Justifies each", "Rejects a noisy feature"],
    hints: ["Which feature matches the query?", "Do users want old or new tickets?", "Which feature is pure noise?"],
    pattern: "Ranking features",
    prerequisites: ["RANK-001"],
    nextQuestionId: "RANK-003",
  }),
  q({
    id: "RANK-003", track: "retrieval", lessonId: "ai-ml/06-retrieval/ranking-is-a-separate-responsibility",
    kind: "debugging",
    prompt: "Debug the reranker that reverses strong evidence: the top candidate has 3 exact keyword matches but ranks 8th.",
    contextFixture: { matches: 3, rank: 8, cause: "a dominant weak feature" },
    expectedArtifact: "A weak feature (e.g. length) overpowers the match signal; inspect feature weights or re-train with match strength emphasized.",
    rubric: ["Finds the dominant feature", "Names the reversal", "Prescribes re-weighting"],
    hints: ["What feature could outvote matches?", "Which feature's scale dominates?", "Reweight or retrain."],
    pattern: "Reranker bug",
    prerequisites: ["RANK-002"],
    nextQuestionId: "RANK-004",
  }),
  q({
    id: "RANK-004", track: "retrieval", lessonId: "ai-ml/06-retrieval/ranking-is-a-separate-responsibility",
    kind: "derivation",
    prompt: "Calculate this ranking metric: relevant docs at positions 1, 3, 5 for a query. Compute MRR.",
    contextFixture: { relevant: [1, 3, 5] },
    expectedArtifact: "MRR = 1/1 = 1.0 (first relevant at rank 1) — reciprocal rank rewards finding something relevant fast.",
    rubric: ["Finds the first relevant", "Takes the reciprocal", "Produces 1.0"],
    hints: ["Where is the first relevant result?", "MRR = 1/rank of first relevant.", "Why does position 1 matter most?"],
    pattern: "MRR",
    prerequisites: ["RANK-001"],
    nextQuestionId: "RANK-005",
  }),
  q({
    id: "RANK-005", track: "retrieval", lessonId: "ai-ml/06-retrieval/ranking-is-a-separate-responsibility",
    kind: "communication",
    prompt: "Explain this relevance-label disagreement: two annotators rated the same (query, doc) pair 3 and 1 out of 5. Write the resolution.",
    contextFixture: { labels: [3, 1], cause: "ambiguous query intent" },
    expectedArtifact: "The disagreement is signal, not noise: adjudicate with a third annotator and a written rubric; measure inter-annotator agreement.",
    rubric: ["Names ambiguity as cause", "Prescribes adjudication", "Adds a rubric"],
    hints: ["Why would two people differ?", "Who settles it?", "How do you measure the gap?"],
    pattern: "Label agreement",
    prerequisites: ["SEARCH-005"],
    nextQuestionId: "REC-001",
  }),
  q({
    id: "REC-001", track: "retrieval", lessonId: "ai-ml/06-retrieval/ranking-is-a-separate-responsibility",
    kind: "implementation",
    prompt: "Build a popularity baseline: rank tickets by total views, ties broken by recency. Write the ordering rule.",
    contextFixture: { metric: "views", tiebreak: "recency" },
    expectedArtifact: "sort by (views desc, created desc) — a zero-learning baseline that should be beaten by any real signal.",
    rubric: ["Uses views", "Breaks ties by recency", "Names it a baseline"],
    hints: ["What is the primary key?", "What decides equal views?", "Is this learning or counting?"],
    pattern: "Popularity baseline",
    prerequisites: ["BASE-003"],
    nextQuestionId: "REC-002",
  }),
  q({
    id: "REC-002", track: "retrieval", lessonId: "ai-ml/06-retrieval/ranking-is-a-separate-responsibility",
    kind: "debugging",
    prompt: "Diagnose the cold-start problem: a brand-new ticket gets no views, so popularity ranks it last, so nobody sees it.",
    contextFixture: { newItem: "0 views", loop: "popularity → no exposure" },
    expectedArtifact: "Popularity starves new content: add exploration (recency boost or pure-random arm) so the loop can start.",
    rubric: ["Names the starvation loop", "Explains the feedback cycle", "Prescribes exploration"],
    hints: ["What feeds the ranking?", "What does a new item need first?", "How do you inject chance?"],
    pattern: "Cold start",
    prerequisites: ["REC-001"],
    nextQuestionId: "REC-003",
  }),
  q({
    id: "REC-003", track: "retrieval", lessonId: "ai-ml/06-retrieval/ranking-is-a-separate-responsibility",
    kind: "debugging",
    prompt: "Identify feedback-loop amplification: the recommender promoted ticket X, views grew, so the recommender promoted X more.",
    contextFixture: { loop: "promote → views → promote" },
    expectedArtifact: "A popularity feedback loop: exposure begets engagement begets exposure — quality never enters; break it with quality-weighted or diversified ranking.",
    rubric: ["Names the loop", "Traces the mechanism", "Prescribes a quality term"],
    hints: ["What feeds the popularity signal?", "What is never measured in the loop?", "How do you add a counterweight?"],
    pattern: "Feedback loop",
    prerequisites: ["REC-002"],
    nextQuestionId: "REC-004",
  }),
  q({
    id: "REC-004", track: "retrieval", lessonId: "ai-ml/06-retrieval/ranking-is-a-separate-responsibility",
    kind: "prediction",
    prompt: "Choose exploration versus exploitation: 90% of traffic ranks by the learned model, 10% by recency/random. Predict what the 10% buys you.",
    contextFixture: { exploit: 90, explore: 10 },
    expectedArtifact: "The 10% keeps the model honest: it samples unseen items, feeds fresh labels, and prevents popularity lock-in — at the cost of 10% suboptimal clicks.",
    rubric: ["States the data purpose", "Names lock-in prevention", "Names the cost"],
    hints: ["Where do new labels come from?", "What happens with 100/0?", "What is sacrificed?"],
    pattern: "Explore vs exploit",
    prerequisites: ["REC-003"],
    nextQuestionId: "REC-005",
  }),
  q({
    id: "REC-005", track: "retrieval", lessonId: "ai-ml/06-retrieval/ranking-is-a-separate-responsibility",
    kind: "construction",
    prompt: "Design a recommendation slice evaluation: mobile vs desktop users, new vs returning.",
    contextFixture: { slices: ["mobile", "desktop", "new", "returning"] },
    expectedArtifact: "Compute click-through and satisfaction per slice; gate on the worst slice (e.g. new users) so one segment can't silently fail.",
    rubric: ["Defines the slices", "Picks per-slice metrics", "Gates on the worst"],
    hints: ["Which segments can diverge?", "What metric per slice?", "Who must not regress?"],
    pattern: "Slice evaluation",
    prerequisites: ["EVAL-004"],
    nextQuestionId: "RAG-001",
  }),
]
