// ai-ml question bank — Track: Classical ML (docs/13).
// MODEL-001 … MODEL-010, UNSUP-001 … UNSUP-005, TREE-ML-001 … TREE-ML-005.

import { q } from "./questions-math"
import type { AiQuestion } from "../../../schema/question"

export const classicalQuestions: AiQuestion[] = [
  q({
    id: "MODEL-001", track: "classical", lessonId: "ai-ml/01-baseline/a-score-is-not-a-prediction",
    kind: "derivation",
    prompt: "Convert these feature weights into a linear score: w = [0.5, -1.0], x = [2, 1]. Show the weighted sum.",
    contextFixture: { w: [0.5, -1.0], x: [2, 1] },
    expectedArtifact: "score = 0.5·2 + (−1)·1 = 0 — a weighted sum, still just a number, not yet a prediction.",
    rubric: ["Multiplies weight by feature", "Sums the products", "Notes score ≠ prediction"],
    hints: ["Multiply each pair first.", "Then add the two products.", "A score is raw; the threshold comes later."],
    pattern: "Linear score",
    prerequisites: [],
    nextQuestionId: "MODEL-002",
  }),
  q({
    id: "MODEL-002", track: "classical", lessonId: "ai-ml/01-baseline/a-score-is-not-a-prediction",
    kind: "prediction",
    prompt: "A false negative (missed bug) costs 10× a false positive. Predict the threshold move and the confusion-matrix tradeoff.",
    contextFixture: { costFN: 10, costFP: 1 },
    expectedTraceObservation: "Lower the threshold: more bugs caught (fewer FN) at the price of more FP — the matrix shifts, accuracy may drop, cost drops.",
    rubric: ["Moves the threshold down", "Names the FP increase", "Frames the choice in cost"],
    hints: ["Which error hurts more?", "To catch more bugs, do you accept more or fewer predictions?", "Threshold tuning is cost accounting, not accuracy."],
    pattern: "Threshold rule",
    prerequisites: ["MODEL-001"],
    nextQuestionId: "MODEL-003",
  }),
  q({
    id: "MODEL-003", track: "classical", lessonId: "ai-ml/02-linear-classifier/learn-by-reducing-error",
    kind: "implementation",
    prompt: "Implement logistic prediction from scratch: score = w·x, then sigmoid. Write the two-line function.",
    contextFixture: { w: [0.5, -1.0], x: [2, 1] },
    expectedArtifact: "def predict(w, x): return 1 / (1 + exp(-dot(w, x))) — output in (0,1), a probability-like score.",
    rubric: ["Computes the dot product", "Applies the sigmoid", "Keeps output in (0,1)"],
    hints: ["What is the score before the squashing?", "Which function maps any real number to (0,1)?", "sigmoid = 1/(1+e^−z)."],
    pattern: "Logistic output",
    prerequisites: ["MODEL-001"],
    nextQuestionId: "MODEL-004",
  }),
  q({
    id: "MODEL-004", track: "classical", lessonId: "ai-ml/02-linear-classifier/learn-by-reducing-error",
    kind: "derivation",
    prompt: "Trace this classifier's loss and gradient for one step: true y=1, predicted p=0.8, weight w=0.5, x=2.",
    contextFixture: { y: 1, p: 0.8, w: 0.5, x: 2, lr: 0.1 },
    expectedArtifact: "Binary cross-entropy −log(0.8) ≈ 0.22; gradient (p−y)·x = −0.4; w_new = 0.5 − 0.1·(−0.4) = 0.54.",
    rubric: ["Computes the loss", "Computes the gradient", "Applies the update"],
    hints: ["For y=1, what is the loss formula?", "Gradient for logistic loss is (p−y)·x.", "w_new = w − lr·grad — mind the sign."],
    pattern: "Loss and gradient",
    prerequisites: ["MODEL-003"],
    nextQuestionId: "MODEL-005",
  }),
  q({
    id: "MODEL-005", track: "classical", lessonId: "ai-ml/02-linear-classifier/learn-by-reducing-error",
    kind: "debugging",
    prompt: "This gradient-descent loop diverges. Debug the sign error: w = w + lr * grad.",
    contextFixture: { code: "w = w + lr * grad", symptom: "loss climbs" },
    expectedArtifact: "The update must subtract the gradient: w = w − lr·grad. Adding climbs toward the maximum.",
    rubric: ["Finds the sign", "Explains the direction", "Names the consequence (climbing)"],
    hints: ["Which direction does the gradient point?", "Does descent move with it or against it?", "The plus sign turns descent into ascent."],
    pattern: "Descent step",
    prerequisites: ["MODEL-004"],
    nextQuestionId: "MODEL-006",
  }),
  q({
    id: "MODEL-006", track: "classical", lessonId: "ai-ml/02-linear-classifier/learn-by-reducing-error",
    kind: "debugging",
    prompt: "The model predicts only 'question' for every row. Diagnose why: check the class balance and the initialization.",
    contextFixture: { balance: "90/10", init: "all weights zero", predictions: ["question only"] },
    expectedArtifact: "Zero initialization + imbalance: the gradient is zero at the start, the majority class wins, and nothing pulls the boundary.",
    rubric: ["Names zero initialization", "Connects to imbalance", "Proposes a fix (balanced init or reweighting)"],
    hints: ["What is the gradient at zero weights?", "Which class dominates the loss?", "How do you break the symmetric start?"],
    pattern: "Imbalance trap",
    prerequisites: ["MODEL-004"],
    nextQuestionId: "MODEL-007",
  }),
  q({
    id: "MODEL-007", track: "classical", lessonId: "ai-ml/03-experiments/regularization-is-a-tradeoff",
    kind: "prediction",
    prompt: "These validation curves cross: train loss falls to 0.1, val loss rises after epoch 30. Choose the regularization strength from the curves.",
    contextFixture: { epochs: 60, valLowestAt: 30 },
    expectedArtifact: "Pick the strength whose val loss is lowest around epoch 30 — after that the gap is pure overfitting.",
    rubric: ["Locates the best epoch", "Reads the gap as overfitting", "Selects strength by val, not train"],
    hints: ["Where does the val curve bottom out?", "What does a widening gap after that mean?", "Stronger regularization moves the bottom left."],
    pattern: "Regularization",
    prerequisites: ["THEORY-004"],
    nextQuestionId: "MODEL-008",
  }),
  q({
    id: "MODEL-008", track: "classical", lessonId: "ai-ml/02-linear-classifier/when-a-good-score-lies",
    kind: "construction",
    prompt: "Calibrate this accurate but overconfident model: 90% correct overall, yet it says 0.99 on 80% of predictions.",
    contextFixture: { accuracy: 0.9, avgConfidence: 0.99 },
    expectedArtifact: "Temperature scaling (or binning) that maps predicted 0.99 to empirical ~0.9; expected calibration error is the check.",
    rubric: ["Names the overconfidence", "Chooses a calibration method", "Picks ECE as the metric"],
    hints: ["What should 0.99 mean on average?", "What method rescales logits?", "How do you measure calibration after the fix?"],
    pattern: "Calibration",
    prerequisites: ["STAT-006"],
    nextQuestionId: "MODEL-009",
  }),
  q({
    id: "MODEL-009", track: "classical", lessonId: "ai-ml/02-linear-classifier/when-a-good-score-lies",
    kind: "prediction",
    prompt: "Predict when this model should abstain: cost of a wrong answer is 10× the cost of saying 'I don't know'.",
    contextFixture: { wrongCost: 10, abstainCost: 1 },
    expectedArtifact: "Abstain whenever p(correct) × 10 < 1 — i.e. confidence below ~0.9; abstention becomes a first-class output.",
    rubric: ["Frames abstention as cost", "Sets a confidence threshold", "States abstain is an output"],
    hints: ["When is guessing more expensive than silence?", "What probability makes guessing worthwhile?", "Abstention is a third class, not a failure."],
    pattern: "Abstention",
    prerequisites: ["MODEL-008"],
    nextQuestionId: "MODEL-010",
  }),
  q({
    id: "MODEL-010", track: "classical", lessonId: "ai-ml/05-failure-lab/find-the-error-family",
    kind: "communication",
    prompt: "Explain one false positive and one false negative of the bug detector to a non-technical stakeholder.",
    contextFixture: { fp: "flagged 'broken' but it was a feature request", fn: "missed 'dashboard shows 0' bug" },
    expectedArtifact: "A short note: FP = a feature request with bug-like words; FN = a bug described in plain words — each error has a mechanism, not a blame.",
    rubric: ["Names the FP mechanism", "Names the FN mechanism", "Avoids blame language"],
    hints: ["Why did the word match happen?", "What made the bug invisible?", "Errors have mechanisms — that is the insight."],
    pattern: "Error taxonomy",
    prerequisites: ["BASE-002"],
    nextQuestionId: "UNSUP-001",
  }),
  q({
    id: "UNSUP-001", track: "classical", lessonId: "ai-ml/04-retrieval/similarity-is-a-representation-choice",
    kind: "prediction",
    prompt: "Choose the number of clusters from this plot: an elbow at k=3, a flat line after. Predict the right k and the risk of choosing k=6.",
    contextFixture: { elbow: 3, flatAfter: 3 },
    expectedArtifact: "k=3; choosing 6 splits real clusters into arbitrary halves — more clusters is not more insight.",
    rubric: ["Reads the elbow", "Rejects the higher k", "States the over-splitting risk"],
    hints: ["Where does the curve stop bending?", "What does each extra cluster add?", "The elbow is the honesty check."],
    pattern: "Cluster choice",
    prerequisites: [],
    nextQuestionId: "UNSUP-002",
  }),
  q({
    id: "UNSUP-002", track: "classical", lessonId: "ai-ml/04-retrieval/similarity-is-a-representation-choice",
    kind: "derivation",
    prompt: "Trace one centroid update: cluster { [0,0], [2,0], [1,1] }. What is the new centroid?",
    contextFixture: { cluster: [[0, 0], [2, 0], [1, 1]] },
    expectedArtifact: "Centroid = mean per dimension = [1, 1/3].",
    rubric: ["Averages each dimension", "Produces the new point", "Explains centroid = mean"],
    hints: ["Average the x values.", "Average the y values.", "The centroid is the mean point of the cluster."],
    pattern: "Centroid update",
    prerequisites: ["UNSUP-001"],
    nextQuestionId: "UNSUP-003",
  }),
  q({
    id: "UNSUP-003", track: "classical", lessonId: "ai-ml/04-retrieval/similarity-is-a-representation-choice",
    kind: "debugging",
    prompt: "Two clusters formed on raw counts instead of scaled features. Identify the cluster created by a scaling error and name the fix.",
    contextFixture: { raw: "one feature spans 0–1000, other 0–1", clusters: "split by the big feature" },
    expectedArtifact: "Distance is dominated by the large-magnitude feature; standardize (z-score) before clustering.",
    rubric: ["Names the magnitude dominance", "Identifies the misleading cluster", "Proposes scaling"],
    hints: ["Which feature drives Euclidean distance?", "What did the clusters actually split on?", "Scale before you measure."],
    pattern: "Scaling error",
    prerequisites: ["UNSUP-002"],
    nextQuestionId: "UNSUP-004",
  }),
  q({
    id: "UNSUP-004", track: "classical", lessonId: "ai-ml/04-retrieval/similarity-is-a-representation-choice",
    kind: "communication",
    prompt: "A 300-feature dataset reduced to 2 dimensions clusters 'nicely'. Explain to the team what the reduction may have discarded.",
    contextFixture: { before: 300, after: 2 },
    expectedArtifact: "A caveat: the 2 axes keep only the largest variance; separations that live in discarded directions vanish from the plot.",
    rubric: ["Names variance-based projection", "States signal may be discarded", "Warns against over-reading plots"],
    hints: ["Which directions does PCA keep?", "Could a label-separating direction be low-variance?", "Pretty plots can lie."],
    pattern: "Dimensionality loss",
    prerequisites: ["INFO-006"],
    nextQuestionId: "UNSUP-005",
  }),
  q({
    id: "UNSUP-005", track: "classical", lessonId: "ai-ml/04-retrieval/similarity-is-a-representation-choice",
    kind: "construction",
    prompt: "Design a manual inspection sample for these clusters: 3 clusters, 1,000 rows, limited review time.",
    contextFixture: { clusters: 3, rows: 1000, reviewBudget: "~30 rows" },
    expectedArtifact: "Stratified sample: ~10 rows per cluster, picked across the cluster's spread (center and edges) — not just the first 30 rows.",
    rubric: ["Stratifies by cluster", "Covers center and edge", "Binds to a small budget"],
    hints: ["What is the sample split?", "Where do you sample inside a cluster?", "30 rows: which 30 carry the most information?"],
    pattern: "Sampling plan",
    prerequisites: ["UNSUP-001"],
    nextQuestionId: "TREE-ML-001",
  }),
  q({
    id: "TREE-ML-001", track: "classical", lessonId: "ai-ml/02-linear-classifier/learn-by-reducing-error",
    kind: "derivation",
    prompt: "Choose a split that reduces impurity for these rows: 8 question, 4 bug, splitting on the word 'crash' separates 4 bug rows cleanly.",
    contextFixture: { rows: [8, 4], split: "crash", cleanSide: [4] },
    expectedArtifact: "Splitting on 'crash' yields a pure leaf (4 bugs, 0 others) — impurity drops to zero on that side.",
    rubric: ["Identifies the pure leaf", "States impurity reduction", "Reads the split's value"],
    hints: ["What lands on the 'crash' side?", "Is that leaf pure?", "A pure leaf needs no further splits."],
    pattern: "Impurity split",
    prerequisites: [],
    nextQuestionId: "TREE-ML-002",
  }),
  q({
    id: "TREE-ML-002", track: "classical", lessonId: "ai-ml/00-data-contract/what-counts-as-training-data",
    kind: "counterexample",
    prompt: "A tree splits perfectly on the feature 'row_id' and reaches 100% training accuracy. Find the feature split that overfits, and name the harm.",
    contextFixture: { feature: "row_id", trainAcc: 1.0 },
    expectedArtifact: "row_id is unique per row — the tree memorized identities, not rules; test accuracy will collapse.",
    rubric: ["Names the memorization feature", "Explains identity ≠ signal", "States the test consequence"],
    hints: ["What is special about row_id?", "Can a rule generalize from an id?", "Perfect training accuracy on a unique key is a smell."],
    pattern: "Memorization",
    prerequisites: ["TREE-ML-001"],
    nextQuestionId: "TREE-ML-003",
  }),
  q({
    id: "TREE-ML-003", track: "classical", lessonId: "ai-ml/02-linear-classifier/learn-by-reducing-error",
    kind: "communication",
    prompt: "Explain why an ensemble of trees is more stable here than a single deep tree, in one paragraph.",
    contextFixture: { single: "high variance", ensemble: "averaged variance" },
    expectedArtifact: "Each tree overfits differently; averaging cancels idiosyncratic errors while preserving the signal — bias stays, variance shrinks.",
    rubric: ["Names variance as the issue", "Explains error cancellation", "States the tradeoff (cost)"],
    hints: ["Where does a single tree fail?", "Do two overfits fail identically?", "Averaging cancels what?"],
    pattern: "Ensemble stability",
    prerequisites: ["TREE-ML-002"],
    nextQuestionId: "TREE-ML-004",
  }),
  q({
    id: "TREE-ML-004", track: "classical", lessonId: "ai-ml/00-data-contract/what-counts-as-training-data",
    kind: "debugging",
    prompt: "Debug this tree: it splits on 'is_from_eval' and achieves 0.99 AUC on the eval set. Find the leaked feature and the evidence.",
    contextFixture: { feature: "is_from_eval", auc: 0.99 },
    expectedArtifact: "The split marker leaks the eval identity; 0.99 AUC is an artifact — drop the feature and re-evaluate.",
    rubric: ["Names the leak", "Explains the 0.99 mechanism", "Prescribes the fix"],
    hints: ["What does that feature correlate with perfectly?", "Why is 0.99 suspicious?", "The eval set is not a test once it leaks."],
    pattern: "Leakage",
    prerequisites: ["THEORY-001"],
    nextQuestionId: "TREE-ML-005",
  }),
  q({
    id: "TREE-ML-005", track: "classical", lessonId: "ai-ml/01-baseline/a-score-is-not-a-prediction",
    kind: "comparison",
    prompt: "Compare nearest-neighbor behavior before and after scaling: feature A spans 0–1000, feature B spans 0–1. What changes?",
    contextFixture: { a: [0, 1000], b: [0, 1] },
    expectedTraceObservation: "Before: A dominates distance, neighbors are chosen on A alone. After scaling: both features matter equally.",
    rubric: ["Names A's domination", "Predicts neighbor changes", "Recommends standardization"],
    hints: ["Which feature moves distances more?", "Who are the nearest neighbors really?", "Scale both features to comparable ranges."],
    pattern: "Scaling error",
    prerequisites: ["UNSUP-003"],
    nextQuestionId: "EXP-001",
  }),
]
