// ai-ml question bank — Track: Deep learning and transformers (docs/13).
// TENSOR-001 … LM-002.

import { q } from "./questions-math"
import type { AiQuestion } from "../../../schema/question"

export const deepQuestions: AiQuestion[] = [
  q({
    id: "TENSOR-001", track: "deep", lessonId: "ai-ml/07-deep-learning/tensors-are-structured-data",
    kind: "debugging",
    prompt: "Repair this tensor shape mismatch: a [32, 4] batch of embeddings must multiply with weights of shape [5, 4] to produce [32, 5].",
    contextFixture: { batch: [32, 4], weights: [5, 4], want: [32, 5] },
    expectedArtifact: "Weights must be [4, 5]: the inner dims (4) must match, so transpose the weight matrix.",
    rubric: ["States the inner-dim rule", "Transposes the weights", "Produces [32, 5]"],
    hints: ["Which dimension must match?", "What shape must the weights have?", "Transpose to align inner dims."],
    pattern: "Shape contracts",
    prerequisites: ["MATH-004"],
    nextQuestionId: "TENSOR-002",
  }),
  q({
    id: "TENSOR-002", track: "deep", lessonId: "ai-ml/07-deep-learning/tensors-are-structured-data",
    kind: "prediction",
    prompt: "Predict the output shape of this batched operation: [32, 8] embeddings reduced over the last axis.",
    contextFixture: { batch: [32, 8], reduceAxis: -1 },
    expectedArtifact: "[32]: the reduction collapses the last axis, the batch survives.",
    rubric: ["Keeps the batch axis", "Collapses the last axis", "Names the output shape"],
    hints: ["Which axis is reduced?", "Which axes survive?", "Reduction over -1 kills the feature axis."],
    pattern: "Shape contracts",
    prerequisites: ["TENSOR-001"],
    nextQuestionId: "TENSOR-003",
  }),
  q({
    id: "TENSOR-003", track: "deep", lessonId: "ai-ml/07-deep-learning/tensors-are-structured-data",
    kind: "implementation",
    prompt: "Implement a mean reduction over the feature axis WITHOUT losing the batch dimension: keep [32, 1] out of [32, 8].",
    contextFixture: { shape: [32, 8], keepdims: true },
    expectedArtifact: "mean(axis=-1, keepdims=True) → [32, 1]; keepdims preserves the axis so broadcasts still work.",
    rubric: ["Reduces the right axis", "Uses keepdims", "Outputs [32, 1]"],
    hints: ["Which axis is the feature axis?", "What does keepdims=True do?", "Why would a bare [32] break later broadcasts?"],
    pattern: "Keepdims",
    prerequisites: ["TENSOR-002"],
    nextQuestionId: "TENSOR-004",
  }),
  q({
    id: "TENSOR-004", track: "deep", lessonId: "ai-ml/07-deep-learning/tensors-are-structured-data",
    kind: "comparison",
    prompt: "Compare dense and sparse memory for this vocabulary: 50,000 tokens, 8 nonzero entries per row, 1 million rows.",
    contextFixture: { vocab: 50000, nz: 8, rows: 1_000_000 },
    expectedArtifact: "Dense 5×10¹⁰ vs sparse 8×10⁶ entries — sparse wins by ~4 orders of magnitude when most entries are zero.",
    rubric: ["Computes dense", "Computes sparse", "States the sparse win"],
    hints: ["How many entries does dense store?", "How many does sparse store?", "Compare the totals."],
    pattern: "Sparse vs dense",
    prerequisites: ["MATH-005"],
    nextQuestionId: "TENSOR-005",
  }),
  q({
    id: "TENSOR-005", track: "deep", lessonId: "ai-ml/07-deep-learning/tensors-are-structured-data",
    kind: "debugging",
    prompt: "Find the operation that causes numerical overflow: exp of logits reaching 800.",
    contextFixture: { logits: 800, op: "softmax" },
    expectedArtifact: "exp(800) overflows; subtract the max logit before exp (softmax stability trick).",
    rubric: ["Names the exp", "Names the overflow", "Prescribes max-subtraction"],
    hints: ["What does exp(800) equal?", "Which layer computes exp?", "Shift the logits before exp."],
    pattern: "Numerical stability",
    prerequisites: [],
    nextQuestionId: "AUTOGRAD-001",
  }),
  q({
    id: "AUTOGRAD-001", track: "deep", lessonId: "ai-ml/07-deep-learning/gradients-are-dependency-accounting",
    kind: "construction",
    prompt: "Draw the computation graph for this scalar expression: L = (a·b + c)² where a, b, c are leaves.",
    contextFixture: { expr: "(a*b + c)^2", leaves: ["a", "b", "c"] },
    expectedArtifact: "a →(×) b →(+) c →(²) L; three ops, four nodes — every intermediate is a node that must record its inputs.",
    rubric: ["Names all ops", "Orders the edges", "Marks leaves and root"],
    hints: ["What does L depend on first?", "Which op combines a and b?", "Every op is a node."],
    pattern: "Computation graph",
    prerequisites: ["OPT-002"],
    nextQuestionId: "AUTOGRAD-002",
  }),
  q({
    id: "AUTOGRAD-002", track: "deep", lessonId: "ai-ml/07-deep-learning/gradients-are-dependency-accounting",
    kind: "derivation",
    prompt: "Propagate one gradient through the graph: dL/dL = 1, L = u², u = a·b. What is dL/da?",
    contextFixture: { L: "u^2", u: "a*b", seed: 1 },
    expectedArtifact: "dL/da = dL/du · du/da = 2u · b = 2·a·b² — the chain rule walks the path from root to leaf.",
    rubric: ["Computes dL/du", "Computes du/da", "Multiplies along the path"],
    hints: ["What is d(u²)/du?", "What is d(a·b)/da?", "Multiply the two steps."],
    pattern: "Backprop",
    prerequisites: ["AUTOGRAD-001"],
    nextQuestionId: "AUTOGRAD-003",
  }),
  q({
    id: "AUTOGRAD-003", track: "deep", lessonId: "ai-ml/07-deep-learning/gradients-are-dependency-accounting",
    kind: "debugging",
    prompt: "Parameter 'b' never receives a gradient, yet it feeds the loss. Find the missing backward edge in this graph.",
    contextFixture: { edge: "b → u missing", symptom: "b.grad = 0" },
    expectedArtifact: "The edge from u back to b is missing (or b is detached): without it the chain cannot reach b, so its gradient stays zero.",
    rubric: ["Finds the missing edge", "Explains the zero gradient", "Names detach as a likely cause"],
    hints: ["Which parameter's grad is zero?", "What must connect it to the loss?", "detach() or a missing edge both sever the chain."],
    pattern: "Backprop",
    prerequisites: ["AUTOGRAD-002"],
    nextQuestionId: "AUTOGRAD-004",
  }),
  q({
    id: "AUTOGRAD-004", track: "deep", lessonId: "ai-ml/07-deep-learning/gradients-are-dependency-accounting",
    kind: "implementation",
    prompt: "Validate this analytic gradient with finite differences: dL/dw = 2w at w = 3, h = 0.001.",
    contextFixture: { analytic: "2w", at: 3, h: 0.001 },
    expectedArtifact: "FD ≈ (9.006001 − 8.994001)/0.002 ≈ 6.0 ≈ analytic 6 — agreement within rounding validates the implementation.",
    rubric: ["Computes finite difference", "Compares to analytic", "States the tolerance"],
    hints: ["Compute L at w+h and w−h.", "Slope = rise over run.", "Compare with 2w."],
    pattern: "Gradient check",
    prerequisites: ["OPT-001"],
    nextQuestionId: "AUTOGRAD-005",
  }),
  q({
    id: "AUTOGRAD-005", track: "deep", lessonId: "ai-ml/07-deep-learning/gradients-are-dependency-accounting",
    kind: "debugging",
    prompt: "One layer's weights never change across 100 epochs. Debug the parameter that never receives a gradient.",
    contextFixture: { symptom: "weights frozen", epoch: 100 },
    expectedArtifact: "The layer is cut from the graph (detach, no requires_grad, or a zero-locality op); verify with a gradient probe at one weight.",
    rubric: ["Narrows to the layer", "Names detach/requires_grad", "Probes with a grad check"],
    hints: ["Where does the chain stop?", "Is the layer tracked?", "Probe one weight's grad."],
    pattern: "Frozen parameter",
    prerequisites: ["AUTOGRAD-003"],
    nextQuestionId: "NN-001",
  }),
  q({
    id: "NN-001", track: "deep", lessonId: "ai-ml/07-deep-learning/compose-a-neural-network",
    kind: "prediction",
    prompt: "Choose an activation for this output contract: binary bug/question with probabilities summing to 1.",
    contextFixture: { contract: "probabilities", classes: 2 },
    expectedArtifact: "Sigmoid (or softmax over 2): the output must be in (0,1) and sum to 1 — ReLU would leak raw scores.",
    rubric: ["Picks sigmoid/softmax", "Justifies the range", "Rejects ReLU"],
    hints: ["What range must the output have?", "What do the two outputs sum to?", "Which activation squashes to (0,1)?"],
    pattern: "Activation contract",
    prerequisites: ["MODEL-003"],
    nextQuestionId: "NN-002",
  }),
  q({
    id: "NN-002", track: "deep", lessonId: "ai-ml/07-deep-learning/compose-a-neural-network",
    kind: "prediction",
    prompt: "Predict how initialization changes activation scale: weights initialized 10× larger than the recommended range.",
    contextFixture: { initScale: "10×", layer: "linear → tanh" },
    expectedTraceObservation: "Pre-activations saturate: tanh outputs pin to ±1, gradients vanish, learning stalls.",
    rubric: ["Predicts saturation", "Names the gradient consequence", "Fixes with proper init scale"],
    hints: ["What does a huge sum do to tanh?", "What is the derivative at ±1?", "Scale init to input size."],
    pattern: "Initialization",
    prerequisites: ["NN-001"],
    nextQuestionId: "NN-003",
  }),
  q({
    id: "NN-003", track: "deep", lessonId: "ai-ml/07-deep-learning/compose-a-neural-network",
    kind: "derivation",
    prompt: "Trace one MLP forward pass: x = [1, 0], W1 = [[1, 0], [0, 1]], no bias, ReLU, output layer W2 = [1, 1].",
    contextFixture: { x: [1, 0], w1: [[1, 0], [0, 1]], w2: [1, 1] },
    expectedArtifact: "h = ReLU([1, 0]) = [1, 0]; y = [1, 1]·[1, 0] = 1.",
    rubric: ["Computes hidden layer", "Applies ReLU", "Computes the output"],
    hints: ["What is W1·x?", "What does ReLU keep?", "Dot W2 with the hidden state."],
    pattern: "Forward pass",
    prerequisites: ["NN-001"],
    nextQuestionId: "NN-004",
  }),
  q({
    id: "NN-004", track: "deep", lessonId: "ai-ml/07-deep-learning/compose-a-neural-network",
    kind: "derivation",
    prompt: "Trace one MLP backward pass: the loss gradient at the output is 1, and the output is 1·h. What is the gradient at h?",
    contextFixture: { dLdy: 1, y: "W2·h", w2: [1, 1] },
    expectedArtifact: "dL/dh = dL/dy · dy/dh = 1 · W2 = [1, 1].",
    rubric: ["Applies the chain rule", "Uses the output weights", "Produces the vector"],
    hints: ["What is dy/dh?", "Multiply the local gradient by the upstream one.", "The gradient flows backward through W2."],
    pattern: "Backward pass",
    prerequisites: ["NN-003"],
    nextQuestionId: "NN-005",
  }),
  q({
    id: "NN-005", track: "deep", lessonId: "ai-ml/07-deep-learning/compose-a-neural-network",
    kind: "debugging",
    prompt: "Diagnose these exploding gradients: loss → NaN after 20 steps, weights become 1e8. Name the mechanism and two fixes.",
    contextFixture: { symptom: "NaN", weights: "1e8", layer: 12 },
    expectedArtifact: "Gradients compound through 12 layers; fix with gradient clipping and smaller init/lr.",
    rubric: ["Names compounding", "Prescribes clipping", "Names init/lr control"],
    hints: ["What multiplies 12 times?", "What caps a step's size?", "Two knobs: step size and start size."],
    pattern: "Exploding gradients",
    prerequisites: ["NN-004"],
    nextQuestionId: "NN-006",
  }),
  q({
    id: "NN-006", track: "deep", lessonId: "ai-ml/07-deep-learning/compose-a-neural-network",
    kind: "debugging",
    prompt: "Diagnose these vanishing gradients: early layers barely move after 200 epochs, tanh activations.",
    contextFixture: { layer: "early", activation: "tanh", epochs: 200 },
    expectedArtifact: "tanh saturates and its derivative → 0; deep multiplications shrink the signal — switch to ReLU-style or add residual paths.",
    rubric: ["Names saturation", "Names the shrink", "Prescribes ReLU/residual"],
    hints: ["What is tanh'(0.99)?", "How many small numbers multiply?", "Which activation keeps gradients alive?"],
    pattern: "Vanishing gradients",
    prerequisites: ["NN-005"],
    nextQuestionId: "NN-007",
  }),
  q({
    id: "NN-007", track: "deep", lessonId: "ai-ml/07-deep-learning/compose-a-neural-network",
    kind: "prediction",
    prompt: "Choose where normalization changes the system: batch norm after the linear layer vs before the activation.",
    contextFixture: { options: ["before activation", "after activation"] },
    expectedArtifact: "Before the activation (on pre-activations): that is where scale drift lives; normalizing saturated outputs is too late.",
    rubric: ["Picks pre-activation", "Explains where scale lives", "Names the stabilizer role"],
    hints: ["Where does scale diverge?", "What does the activation see?", "Normalize the raw signal."],
    pattern: "Normalization",
    prerequisites: ["NN-005"],
    nextQuestionId: "NN-008",
  }),
  q({
    id: "NN-008", track: "deep", lessonId: "ai-ml/07-deep-learning/compose-a-neural-network",
    kind: "operations",
    prompt: "Resume training from this checkpoint: epoch 40 of 100, loss 0.31. What must the resume verify before continuing?",
    contextFixture: { epoch: 40, loss: 0.31, state: "weights + optimizer" },
    expectedArtifact: "Verify weights AND optimizer state (momentum), the data order/seed, and the loss matches — a weights-only resume restarts optimizer history.",
    rubric: ["Includes optimizer state", "Checks data order", "Verifies loss continuity"],
    hints: ["What else does the optimizer keep?", "What shuffles on restart?", "Loss should continue, not reset."],
    pattern: "Checkpointing",
    prerequisites: ["EXP-004"],
    nextQuestionId: "NN-009",
  }),
  q({
    id: "NN-009", track: "deep", lessonId: "ai-ml/07-deep-learning/compose-a-neural-network",
    kind: "comparison",
    prompt: "Compare batch and mini-batch updates: batch 512 vs mini-batch 16 on the same data. Predict the loss-curve difference.",
    contextFixture: { batch: 512, mini: 16 },
    expectedTraceObservation: "Batch: smooth, stable steps, more compute per step. Mini-batch: noisier steps, faster updates, often escapes flat regions — but noisier.",
    rubric: ["Predicts smooth vs noisy", "Notes update frequency", "States the tradeoff"],
    hints: ["What averages a big batch?", "How often does a mini-batch update?", "Noise can help or hurt."],
    pattern: "Batch size",
    prerequisites: ["NN-004"],
    nextQuestionId: "NN-010",
  }),
  q({
    id: "NN-010", track: "deep", lessonId: "ai-ml/07-deep-learning/compose-a-neural-network",
    kind: "communication",
    prompt: "Explain why this model memorizes training data: 40M parameters, 30K training rows, accuracy 1.0/0.62 train/test.",
    contextFixture: { params: "40M", rows: "30K", acc: [1.0, 0.62] },
    expectedArtifact: "Capacity ≫ data: 40M parameters can store 30K rows verbatim; the test gap is memorization, not learning.",
    rubric: ["Compares capacity to data", "Reads the train/test gap", "Names memorization"],
    hints: ["What can 40M numbers store?", "What does 1.0 vs 0.62 mean?", "Parameters can memorize rows."],
    pattern: "Memorization",
    prerequisites: ["THEORY-002"],
    nextQuestionId: "ATTN-001",
  }),
  q({
    id: "ATTN-001", track: "deep", lessonId: "ai-ml/07-deep-learning/context-changes-representation",
    kind: "construction",
    prompt: "Construct queries, keys, and values for this sentence: 'the model failed'. One token, one vector each.",
    contextFixture: { tokens: ["the", "model", "failed"], dim: 4 },
    expectedArtifact: "Three Q, three K, three V vectors (e.g. per-token linear projections); Q asks, K answers 'who am I', V carries the content.",
    rubric: ["Produces Q/K/V per token", "Separates the three roles", "Keeps shapes consistent"],
    hints: ["What asks the question?", "What gets matched against?", "What carries the content?"],
    pattern: "QKV",
    prerequisites: ["NN-003"],
    nextQuestionId: "ATTN-002",
  }),
  q({
    id: "ATTN-002", track: "deep", lessonId: "ai-ml/07-deep-learning/context-changes-representation",
    kind: "derivation",
    prompt: "Calculate one attention score: Q1 = [1, 0], K2 = [0, 1], scale = √2. What is the pre-softmax score between token 1 and token 2?",
    contextFixture: { q1: [1, 0], k2: [0, 1], scale: "sqrt(2)" },
    expectedArtifact: "score = (1·0 + 0·1)/√2 = 0 — orthogonal directions contribute nothing.",
    rubric: ["Dots Q and K", "Divides by the scale", "Interprets the result"],
    hints: ["Compute Q1 · K2.", "Divide by √2.", "Orthogonal means no affinity."],
    pattern: "Attention score",
    prerequisites: ["ATTN-001"],
    nextQuestionId: "ATTN-003",
  }),
  q({
    id: "ATTN-003", track: "deep", lessonId: "ai-ml/07-deep-learning/context-changes-representation",
    kind: "implementation",
    prompt: "Apply this causal mask to a 3-token attention matrix: tokens may only attend to themselves and earlier tokens.",
    contextFixture: { matrix: 3, mask: "future = -inf" },
    expectedArtifact: "Row i keeps columns ≤ i; entries above the diagonal become −inf so softmax gives them zero weight.",
    rubric: ["Masks future positions", "Uses −inf not zero", "Keeps diagonal"],
    hints: ["Which cells are forbidden?", "What value zeroes a softmax entry?", "Can a token see itself?"],
    pattern: "Causal masking",
    prerequisites: ["ATTN-002"],
    nextQuestionId: "ATTN-004",
  }),
  q({
    id: "ATTN-004", track: "deep", lessonId: "ai-ml/07-deep-learning/context-changes-representation",
    kind: "prediction",
    prompt: "Predict how context changes this token representation: 'bank' appears first with 'river' and then with 'money'.",
    contextFixture: { token: "bank", contexts: ["river", "money"] },
    expectedTraceObservation: "The attention output blends V of context tokens into 'bank's representation — the same token shifts meaning by context.",
    rubric: ["Names the blending", "Predicts meaning shift", "Points at attention weights"],
    hints: ["What does attention mix into the token?", "Do the two contexts weigh differently?", "Representation becomes context-conditioned."],
    pattern: "Context conditioning",
    prerequisites: ["ATTN-002"],
    nextQuestionId: "ATTN-005",
  }),
  q({
    id: "ATTN-005", track: "deep", lessonId: "ai-ml/07-deep-learning/context-changes-representation",
    kind: "communication",
    prompt: "Inspect this attention failure: the model attends to the padding token at the end of every sentence. Explain the mechanism and the harm.",
    contextFixture: { attention: "→ padding", harm: "noise pollutes the context" },
    expectedArtifact: "Padding is still attended (softmax over all positions); the model leaks meaningless mass — fix with masking padding out of attention.",
    rubric: ["Names padding attention", "States the softmax mechanism", "Prescribes masking"],
    hints: ["Where does the mass go?", "What does softmax sum over?", "What should be excluded?"],
    pattern: "Padding leak",
    prerequisites: ["ATTN-003"],
    nextQuestionId: "ATTN-006",
  }),
  q({
    id: "ATTN-006", track: "deep", lessonId: "ai-ml/07-deep-learning/context-changes-representation",
    kind: "comparison",
    prompt: "Compare one head and multiple heads: single-head attention captures one relationship per position. What do multiple heads add?",
    contextFixture: { one: "one relationship", many: "parallel relationships" },
    expectedArtifact: "Multiple heads attend to different relationship types (syntax, proximity, coreference) in parallel and concatenate — more expressive, same cost scaling.",
    rubric: ["Names parallel relationships", "Explains concatenation", "Notes the cost"],
    hints: ["Can one weight pattern catch two relationships?", "How do heads run together?", "What changes in the output?"],
    pattern: "Multi-head",
    prerequisites: ["ATTN-004"],
    nextQuestionId: "ATTN-007",
  }),
  q({
    id: "ATTN-007", track: "deep", lessonId: "ai-ml/07-deep-learning/context-changes-representation",
    kind: "derivation",
    prompt: "Explain the cost of a longer context: attention is all-pairs. How does the compute scale with context length n?",
    contextFixture: { n: "context length" },
    expectedArtifact: "O(n²) attention pairs (and O(n²) memory): doubling the context quadruples the cost — the reason for chunking and sparse attention.",
    rubric: ["States O(n²)", "Notes memory too", "Names the mitigation"],
    hints: ["How many pairs does n tokens form?", "What must be stored?", "Quadratic growth needs tricks."],
    pattern: "Attention cost",
    prerequisites: ["ATTN-002"],
    nextQuestionId: "ATTN-008",
  }),
  q({
    id: "ATTN-008", track: "deep", lessonId: "ai-ml/07-deep-learning/context-changes-representation",
    kind: "debugging",
    prompt: "Debug this positional-information bug: the model treats 'dog bites man' and 'man bites dog' as identical.",
    contextFixture: { symptom: "order ignored", cause: "no positional encoding" },
    expectedArtifact: "Without positional encoding the representation is a bag of tokens; add positional information to the input embeddings.",
    rubric: ["Names the missing encoding", "Explains permutation invariance", "Prescribes positional embeddings"],
    hints: ["What distinguishes the two sentences?", "Does the model see order at all?", "Inject position into the input."],
    pattern: "Positional encoding",
    prerequisites: ["ATTN-001"],
    nextQuestionId: "LM-001",
  }),
  q({
    id: "LM-001", track: "deep", lessonId: "ai-ml/07-deep-learning/build-a-tiny-language-model",
    kind: "derivation",
    prompt: "Calculate next-token cross-entropy: the true next token is 'bug', the model assigns it probability 0.1.",
    contextFixture: { trueToken: "bug", p: 0.1 },
    expectedArtifact: "−log(0.1) ≈ 2.30 nats — the loss punishes low probability on the true token.",
    rubric: ["Uses the true-token probability", "Applies −log", "Computes ≈ 2.30"],
    hints: ["Which probability does the loss read?", "What is −log(0.1)?", "Low truth probability → high loss."],
    pattern: "Cross-entropy",
    prerequisites: ["INFO-002"],
    nextQuestionId: "LM-002",
  }),
  q({
    id: "LM-002", track: "deep", lessonId: "ai-ml/07-deep-learning/build-a-tiny-language-model",
    kind: "comparison",
    prompt: "Compare temperature and top-k sampling: temperature 1.5 vs 0.2, and top-k 5 vs 50. Predict the style of each generation.",
    contextFixture: { temp: [1.5, 0.2], topK: [5, 50] },
    expectedTraceObservation: "High temperature + large k → varied, riskier text; low temperature + small k → predictable, repetitive text; the two knobs bound the distribution.",
    rubric: ["Predicts temperature effect", "Predicts top-k effect", "Explains the interplay"],
    hints: ["What does high temperature do to probabilities?", "What does top-k cut?", "Both shape the sampling distribution."],
    pattern: "Sampling",
    prerequisites: ["LM-001"],
    nextQuestionId: "SEARCH-001",
  }),
]
