// ai-ml question bank — Track: Mathematics and theory (docs/13 §180 bank).
// MATH-001 … THEORY-006. Authored data, deterministic fixtures, question-first hints.

import type { AiQuestion } from "../../../schema/question"

export type { AiQuestion }

export function q(x: Omit<AiQuestion, "reviewIntervals"> & { reviewIntervals?: number[] }): AiQuestion {
  return { reviewIntervals: [1, 7, 30], ...x } as AiQuestion
}

export const mathQuestions: AiQuestion[] = [
  q({
    id: "MATH-001", track: "math", lessonId: "ai-ml/07-deep-learning/tensors-are-structured-data",
    kind: "prediction",
    prompt: "A batch of 32 support tickets each has 4 features. Three new features are added to every row. What shape does the batch have now?",
    contextFixture: { batch: 32, features: 4, added: 3 },
    expectedArtifact: "Shape (32, 7): the batch dimension never changes when features are added per row.",
    rubric: ["Names a two-element shape", "Keeps the batch dimension (32) unchanged", "Adds the feature counts (4 + 3 = 7)"],
    hints: ["Which axis counts rows, and which counts columns?", "Does adding a feature per row touch the row count or the column count?", "Write it as (rows, columns) — the first number is fixed."],
    pattern: "Shape contracts",
    prerequisites: [],
    nextQuestionId: "MATH-002",
  }),
  q({
    id: "MATH-002", track: "math", lessonId: "ai-ml/07-deep-learning/tensors-are-structured-data",
    kind: "derivation",
    prompt: "Why does a dot product rank document A higher than document B for this query, when they share the same vocabulary size?",
    contextFixture: { query: [1, 0, 2], docA: [2, 0, 1], docB: [1, 1, 1] },
    expectedTraceObservation: "query · docA = 2+0+2 = 4 > query · docB = 1+0+2 = 3; the weight on the overlapping terms decides.",
    rubric: ["Computes both dot products", "Identifies which term dominates", "States that shared, heavy terms decide ranking"],
    hints: ["Multiply each query weight by the matching document weight.", "Which document aligns more with the query's strongest term?", "A dot product rewards overlap on weighted terms — write both totals."],
    pattern: "Weighted overlap",
    prerequisites: ["MATH-001"],
    nextQuestionId: "MATH-003",
  }),
  q({
    id: "MATH-003", track: "math", lessonId: "ai-ml/04-retrieval/similarity-is-a-representation-choice",
    kind: "prediction",
    prompt: "Compute the cosine similarity of these two vectors. Which of the three options is correct?",
    contextFixture: { a: [1, 0], b: [1, 1] },
    expectedArtifact: "cos = 1/(1·√2) = 0.707 — magnitude is normalized away, angle remains.",
    rubric: ["Computes both magnitudes", "Computes the dot product", "Divides dot product by the product of magnitudes"],
    hints: ["First: what is the length of each vector?", "The dot product of [1,0] and [1,1] is what?", "Cosine = dot ÷ (|a| × |b|)."],
    pattern: "Normalized similarity",
    prerequisites: ["MATH-002"],
    nextQuestionId: "MATH-004",
  }),
  q({
    id: "MATH-004", track: "math", lessonId: "ai-ml/07-deep-learning/tensors-are-structured-data",
    kind: "debugging",
    prompt: "This matrix product is rejected at runtime. Which multiplication is invalid, and what is the rule that catches it?",
    contextFixture: { a: [2, 3], b: [3, 4], c: [2, 4], attempts: ["a×b", "b×c", "a×c"] },
    expectedArtifact: "a×c is invalid: inner dimensions 3 ≠ 2. The inner dimension of the left matrix must equal the rows of the right.",
    rubric: ["Finds the invalid pair", "States the inner-dimension rule", "Explains the cost of the valid products"],
    hints: ["What must the columns of the left matrix match?", "Write the dimensions as (2×3)(3×4) — which pair breaks the chain?", "The invalid one has mismatched inner dimensions."],
    pattern: "Shape contracts",
    prerequisites: ["MATH-001"],
    nextQuestionId: "MATH-005",
  }),
  q({
    id: "MATH-005", track: "math", lessonId: "ai-ml/07-deep-learning/tensors-are-structured-data",
    kind: "prediction",
    prompt: "A vocabulary of 20,000 tokens is stored as one-hot rows. A sparse representation uses only the 8 nonzero positions per row. Which is smaller, and by roughly how much?",
    contextFixture: { vocab: 20000, nonzeroPerRow: 8, rows: 1000 },
    expectedArtifact: "Sparse: 1000×8 vs dense 1000×20000 — a ~2500× saving, because only nonzero positions are stored.",
    rubric: ["Computes both footprints", "States sparse wins", "Explains why (zero positions dominate dense)"],
    hints: ["How many numbers does dense store per row?", "How many does sparse store per row?", "Compare the totals, not the shapes."],
    pattern: "Sparse vs dense",
    prerequisites: ["MATH-001"],
    nextQuestionId: "MATH-006",
  }),
  q({
    id: "MATH-006", track: "math", lessonId: "ai-ml/07-deep-learning/tensors-are-structured-data",
    kind: "debugging",
    prompt: "This broadcast fails. Repair it without changing the batch dimension: add a text column to [32, 4] using a [32] vector of lengths.",
    contextFixture: { batch: [32, 4], lengths: [32], op: "batch + lengths" },
    expectedArtifact: "lengths must reshape to [32, 1] (or [32, 1, 1]) so trailing dimensions align as [32, 4] + [32, 1].",
    rubric: ["Identifies the shape mismatch", "Keeps the batch dimension", "Reshapes the vector to align trailing dims"],
    hints: ["Broadcasting aligns trailing dimensions — which axis is missing?", "A [32] vector pairs against the last axis, not the first.", "Add a singleton axis on the vector."],
    pattern: "Broadcasting",
    prerequisites: ["MATH-004"],
    nextQuestionId: "STAT-001",
  }),
  q({
    id: "STAT-001", track: "math", lessonId: "ai-ml/01-baseline/the-baseline-earns-the-right-to-improve",
    kind: "prediction",
    prompt: "A survey is sent only to users who visited the settings page last week. Which sampling process does this create, and what does it bias?",
    contextFixture: { population: "all users", sample: "settings visitors" },
    expectedTraceObservation: "Selection bias: the sample over-represents engaged users; estimates of satisfaction are not population estimates.",
    rubric: ["Names the bias", "Names what is over-represented", "States what conclusions are unsafe"],
    hints: ["Who is in the sample, and who is silently excluded?", "Does the sample look like the population in behavior?", "A sample that excludes a group cannot speak for it."],
    pattern: "Sampling bias",
    prerequisites: [],
    nextQuestionId: "STAT-002",
  }),
  q({
    id: "STAT-002", track: "math", lessonId: "ai-ml/01-baseline/the-baseline-earns-the-right-to-improve",
    kind: "prediction",
    prompt: "90% of tickets are 'question', 10% are 'bug'. A model predicts 'question' for every ticket. What is its accuracy — and why is that number dangerous?",
    contextFixture: { question: 90, bug: 10 },
    expectedArtifact: "Accuracy 90% — the majority-class baseline. It hides that the model detects zero bugs.",
    rubric: ["Computes the accuracy", "Names it the majority baseline", "States the hidden failure (0 recall on bugs)"],
    hints: ["How often is the always-question guess right?", "What does it get wrong every single time?", "An accuracy that ignores the minority class is a number that lies."],
    pattern: "Baseline honesty",
    prerequisites: ["STAT-001"],
    nextQuestionId: "STAT-003",
  }),
  q({
    id: "STAT-003", track: "math", lessonId: "ai-ml/02-linear-classifier/when-a-good-score-lies",
    kind: "derivation",
    prompt: "From this confusion matrix, calculate precision, recall, and F1 for the bug class.",
    contextFixture: { tp: 40, fp: 10, fn: 60, tn: 890 },
    expectedArtifact: "precision 40/50 = 0.8 · recall 40/100 = 0.4 · F1 = 2·(0.8·0.4)/(1.2) ≈ 0.53",
    rubric: ["Computes precision", "Computes recall", "Combines them into F1"],
    hints: ["Precision = tp ÷ (tp + fp) — of what was predicted bug, how much was right?", "Recall = tp ÷ (tp + fn) — of all real bugs, how many were found?", "F1 is the harmonic mean of the two."],
    pattern: "Metric algebra",
    prerequisites: ["STAT-002"],
    nextQuestionId: "STAT-004",
  }),
  q({
    id: "STAT-004", track: "math", lessonId: "ai-ml/02-linear-classifier/when-a-good-score-lies",
    kind: "comparison",
    prompt: "Two confidence intervals estimate the same mean: [0.42, 0.58] and [0.47, 0.53]. Which is narrower, and what caused the difference?",
    contextFixture: { intervalA: [0.42, 0.58], intervalB: [0.47, 0.53], samples: [100, 400] },
    expectedTraceObservation: "B's interval is narrower; with more data the standard error shrinks, so the interval tightens.",
    rubric: ["Picks the narrower interval", "Attributes it to sample size", "Explains standard error shrinking"],
    hints: ["Which interval has less spread?", "Which sample size produced each?", "More data → smaller standard error → ?"],
    pattern: "Evidence vs claims",
    prerequisites: ["STAT-001"],
    nextQuestionId: "STAT-005",
  }),
  q({
    id: "STAT-005", track: "math", lessonId: "ai-ml/01-baseline/the-baseline-earns-the-right-to-improve",
    kind: "counterexample",
    prompt: "Users who open the onboarding email also finish onboarding at higher rates. Construct a reason why this correlation is NOT evidence that the email causes completion.",
    contextFixture: { claim: "email → completion", hidden: "already-active users open emails more" },
    expectedArtifact: "A hidden confounder (prior engagement) drives both; the email is not the cause — randomization would be needed.",
    rubric: ["Names a confounder", "Explains the causal gap", "Proposes the experiment that would settle it"],
    hints: ["What kind of user opens onboarding emails in the first place?", "Could that trait explain completion on its own?", "How would you test the email without correlation confounds?"],
    pattern: "Correlation vs causation",
    prerequisites: ["STAT-001"],
    nextQuestionId: "STAT-006",
  }),
  q({
    id: "STAT-006", track: "math", lessonId: "ai-ml/02-linear-classifier/when-a-good-score-lies",
    kind: "debugging",
    prompt: "A model says 0.9 for every prediction, yet it is wrong on half of them. Diagnose this calibration failure and name the fix.",
    contextFixture: { predicted: 0.9, accuracy: 0.5 },
    expectedArtifact: "Overconfident and miscalibrated: predicted probability ≠ observed frequency. Fix with calibration (temperature or binning).",
    rubric: ["Names the miscalibration", "States predicted ≠ observed", "Names a calibration technique"],
    hints: ["If it says 0.9 forever, how often should it be right?", "It is right 50% — what does 0.9 mean then?", "The fix realigns predicted probability with empirical frequency."],
    pattern: "Calibration",
    prerequisites: ["STAT-003"],
    nextQuestionId: "OPT-001",
  }),
  q({
    id: "OPT-001", track: "math", lessonId: "ai-ml/02-linear-classifier/learn-by-reducing-error",
    kind: "derivation",
    prompt: "Estimate the derivative of f(x) = x² at x = 3 using a finite difference with h = 0.01.",
    contextFixture: { fn: "x^2", at: 3, h: 0.01 },
    expectedArtifact: "(9.0601 − 8.9401)/0.02 = 6.00 — within rounding of the true derivative 2x = 6.",
    rubric: ["Evaluates f at both points", "Divides by the span", "Compares to the analytic answer"],
    hints: ["Compute f(3.01) and f(2.99).", "The slope is rise over run between those points.", "Compare with 2×3."],
    pattern: "Finite differences",
    prerequisites: [],
    nextQuestionId: "OPT-002",
  }),
  q({
    id: "OPT-002", track: "math", lessonId: "ai-ml/02-linear-classifier/learn-by-reducing-error",
    kind: "derivation",
    prompt: "Derive the gradient of this one-parameter squared loss L = (w·x − y)² with respect to w.",
    contextFixture: { loss: "(w*x - y)^2" },
    expectedArtifact: "dL/dw = 2·(w·x − y)·x — the chain rule on the squared error.",
    rubric: ["Applies the chain rule", "Keeps the inner error factor", "Multiplies by x"],
    hints: ["Let u = w·x − y; what is d(u²)/du?", "What is du/dw?", "Multiply the two derivatives."],
    pattern: "Chain rule",
    prerequisites: ["OPT-001"],
    nextQuestionId: "OPT-003",
  }),
  q({
    id: "OPT-003", track: "math", lessonId: "ai-ml/02-linear-classifier/learn-by-reducing-error",
    kind: "prediction",
    prompt: "Trace one gradient-descent update by hand: w = 1.0, learning rate 0.1, gradient 2.0. What is the next w?",
    contextFixture: { w: 1.0, lr: 0.1, grad: 2.0 },
    expectedArtifact: "w_new = 1.0 − 0.1 × 2.0 = 0.8.",
    rubric: ["Subtracts the step from w", "Multiplies lr by gradient", "Arrives at 0.8"],
    hints: ["Which direction does descent move — with or against the gradient?", "How big is the step (lr × gradient)?", "w_new = w − lr·grad."],
    pattern: "Descent step",
    prerequisites: ["OPT-002"],
    nextQuestionId: "OPT-004",
  }),
  q({
    id: "OPT-004", track: "math", lessonId: "ai-ml/03-experiments/the-learning-rate-is-a-system-choice",
    kind: "prediction",
    prompt: "A run converges at learning rate 0.01. Predict the effect of doubling the learning rate to 0.02 on this same convex loss.",
    contextFixture: { lr: [0.01, 0.02], loss: "convex quadratic" },
    expectedTraceObservation: "Faster initial descent, larger oscillation at the bottom; may still converge, but less stably — doubling is not free.",
    rubric: ["Predicts faster initial descent", "Predicts larger oscillation", "Notes it may still converge"],
    hints: ["What does a bigger step do early in the run?", "What happens as the steps approach the minimum?", "Is bigger always better?"],
    pattern: "Learning rate",
    prerequisites: ["OPT-003"],
    nextQuestionId: "OPT-005",
  }),
  q({
    id: "OPT-005", track: "math", lessonId: "ai-ml/02-linear-classifier/learn-by-reducing-error",
    kind: "debugging",
    prompt: "In this loss trace, the loss explodes to NaN after step 40. Find the exploding update and name the cause.",
    contextFixture: { trace: "step 39: 2.1 → step 40: 38.4 → step 41: NaN", lr: 0.5 },
    expectedArtifact: "The step (lr × gradient) overshoots into divergence; lr is too large for this loss surface.",
    rubric: ["Points at the update step", "Names lr as the cause", "States the fix (reduce lr or clip)"],
    hints: ["Compare the jump size at step 40 with earlier jumps.", "What multiplier controls step size?", "The fix is a smaller lr or gradient clipping."],
    pattern: "Divergence",
    prerequisites: ["OPT-004"],
    nextQuestionId: "OPT-006",
  }),
  q({
    id: "OPT-006", track: "math", lessonId: "ai-ml/03-experiments/the-learning-rate-is-a-system-choice",
    kind: "construction",
    prompt: "A batch must fit in 512 MB. Each row costs 4 KB of memory per feature and there are 10 features. Choose the largest safe batch size and justify it.",
    contextFixture: { memory: 512 * 1024 * 1024, bytesPerFeature: 4096, features: 10 },
    expectedArtifact: "row cost 40 KB → 512 MB / 40 KB ≈ 13,107 rows; keep headroom, choose ≤ 12,000.",
    rubric: ["Computes per-row cost", "Divides memory by row cost", "Leaves headroom and justifies"],
    hints: ["How much memory does one row need?", "How many rows fit in the budget?", "Why not take the exact maximum?"],
    pattern: "Memory budget",
    prerequisites: ["OPT-003"],
    nextQuestionId: "INFO-001",
  }),
  q({
    id: "INFO-001", track: "math", lessonId: "ai-ml/07-deep-learning/build-a-tiny-language-model",
    kind: "derivation",
    prompt: "Calculate the entropy of these two label distributions: A = {0.5, 0.5} and B = {0.9, 0.1}.",
    contextFixture: { a: [0.5, 0.5], b: [0.9, 0.1] },
    expectedArtifact: "H(A) = 1.0 bit · H(B) ≈ 0.47 bits — a more certain distribution carries less surprise.",
    rubric: ["Computes H(A)", "Computes H(B)", "States which is more uncertain and why"],
    hints: ["H = −Σ p·log₂(p).", "Which distribution predicts less often?", "Uniform means maximum surprise."],
    pattern: "Entropy",
    prerequisites: [],
    nextQuestionId: "INFO-002",
  }),
  q({
    id: "INFO-002", track: "math", lessonId: "ai-ml/07-deep-learning/build-a-tiny-language-model",
    kind: "derivation",
    prompt: "The true label is class 0; the model outputs 0.99 for class 1. Why does cross-entropy punish this confident wrong prediction so hard?",
    contextFixture: { truth: 0, predictedClass1: 0.99 },
    expectedArtifact: "Cross-entropy uses −log p(true); p(true) = 0.01 → −log(0.01) ≈ 4.6 nats — a confident wrong answer pays a huge penalty.",
    rubric: ["Identifies the true-class probability", "Applies −log", "States confident-wrong is punished most"],
    hints: ["What probability does the loss read — the predicted class or the true class?", "Compute −log(0.01).", "A certain wrong answer is the worst kind of wrong."],
    pattern: "Cross-entropy",
    prerequisites: ["INFO-001"],
    nextQuestionId: "INFO-003",
  }),
  q({
    id: "INFO-003", track: "math", lessonId: "ai-ml/07-deep-learning/build-a-tiny-language-model",
    kind: "construction",
    prompt: "Tokenize 'run-run' under the vocabulary ['run', 'un', '-', 'run-'] with longest-match-first. Show your token sequence.",
    contextFixture: { text: "run-run", vocab: ["run", "un", "-", "run-"] },
    expectedArtifact: "'run-' (4) then 'run' → ['run-', 'run']; longest match wins at each position.",
    rubric: ["Uses longest-match-first", "Produces a valid token sequence", "Spans the whole string"],
    hints: ["At position 0, which vocab entry is longest?", "What remains after that token?", "Cover the whole string exactly."],
    pattern: "Tokenization",
    prerequisites: ["INFO-001"],
    nextQuestionId: "INFO-004",
  }),
  q({
    id: "INFO-004", track: "math", lessonId: "ai-ml/07-deep-learning/build-a-tiny-language-model",
    kind: "debugging",
    prompt: "A tokenizer is given a 12-character string but returns 14 tokens. Find the tokenization that creates this inflated context and fix it.",
    contextFixture: { text: "abcdefghijkl", badTokens: 14 },
    expectedArtifact: "A single-character fallback token splits characters that a longer vocabulary entry should absorb; the fix is longest-match-first.",
    rubric: ["Names the single-char fallback", "Explains the length inflation", "States longest-match as the fix"],
    hints: ["What produces MORE tokens than characters?", "Would a longer vocabulary entry absorb adjacent chars?", "Longest-match-first fixes it."],
    pattern: "Tokenization",
    prerequisites: ["INFO-003"],
    nextQuestionId: "INFO-005",
  }),
  q({
    id: "INFO-005", track: "math", lessonId: "ai-ml/00-data-contract/features-are-a-decision",
    kind: "comparison",
    prompt: "A dataset has 20,000 rare words across 5,000 rows. Choose sparse bag-of-words or dense embeddings and justify your choice for a small classifier.",
    contextFixture: { vocab: 20000, rows: 5000, denseDim: 64 },
    expectedTraceObservation: "Sparse wins here: 5,000×20,000 is mostly zeros; a 64-dim dense representation is smaller but loses word identity — justify by task.",
    rubric: ["Compares both footprints", "Picks a representation for the task", "States the tradeoff (size vs identity)"],
    hints: ["How much of a 5000×20000 bag-of-words is zeros?", "What do dense embeddings preserve and lose?", "Which fits a small classifier on a phone?"],
    pattern: "Sparse vs dense",
    prerequisites: ["MATH-005"],
    nextQuestionId: "INFO-006",
  }),
  q({
    id: "INFO-006", track: "math", lessonId: "ai-ml/04-retrieval/similarity-is-a-representation-choice",
    kind: "communication",
    prompt: "A dimensionality reduction of ticket texts to 2 dimensions lost the bug/question distinction. Identify what the reduction discarded and write the lesson for the team.",
    contextFixture: { before: 300, features: 2, lost: "label-separating direction" },
    expectedArtifact: "A memo: the discarded variance held the signal; 2 dims were chosen by variance, not by label separation.",
    rubric: ["Names what was discarded", "Explains why variance ≠ signal", "Writes an actionable conclusion"],
    hints: ["Which axis did the reduction keep?", "Was the useful direction high-variance?", "Variance and label separation are different things."],
    pattern: "Dimensionality loss",
    prerequisites: ["MATH-005"],
    nextQuestionId: "THEORY-001",
  }),
  q({
    id: "THEORY-001", track: "math", lessonId: "ai-ml/00-data-contract/what-counts-as-training-data",
    kind: "counterexample",
    prompt: "A feature 'is_from_training_batch' is added to every row to help the model. Find the train/test leakage in this feature and state the harm.",
    contextFixture: { feature: "is_from_training_batch", values: { train: 1, eval: 0 } },
    expectedArtifact: "The feature encodes the split itself — the model 'learns' which set it is in; eval becomes trivial and unreal.",
    rubric: ["Identifies the leak", "States the mechanism (split marker)", "States the harm (unreal eval)"],
    hints: ["What does this feature correlate with perfectly?", "If the eval set always has 0, what can the model exploit?", "A feature that reveals the split is a leak."],
    pattern: "Leakage",
    prerequisites: [],
    nextQuestionId: "THEORY-002",
  }),
  q({
    id: "THEORY-002", track: "math", lessonId: "ai-ml/03-experiments/regularization-is-a-tradeoff",
    kind: "prediction",
    prompt: "Which of these two models will overfit the training set, and why: a 2-parameter linear model or a 200-parameter polynomial on 30 rows?",
    contextFixture: { rows: 30, params: [2, 200] },
    expectedTraceObservation: "The 200-parameter model interpolates the 30 points; capacity far exceeds data → memorization, poor generalization.",
    rubric: ["Picks the high-capacity model", "Compares capacity to data size", "Explains memorization vs generalization"],
    hints: ["How many free parameters fit how many points exactly?", "What can 200 parameters do to 30 points?", "Memorizing is not learning."],
    pattern: "Bias vs variance",
    prerequisites: [],
    nextQuestionId: "THEORY-003",
  }),
  q({
    id: "THEORY-003", track: "math", lessonId: "ai-ml/05-failure-lab/find-the-error-family",
    kind: "construction",
    prompt: "Construct a distribution shift that breaks this model: trained on weekday ticket traffic, served on weekends.",
    contextFixture: { train: "weekdays", serve: "weekends" },
    expectedArtifact: "Weekend traffic is thinner and longer-tailed; the model's threshold tuned on weekday volume now misfires.",
    rubric: ["Names the shifted variable", "Explains why training evidence is wrong", "Names a monitoring response"],
    hints: ["What changes between weekdays and weekends?", "Which learned quantity depends on that?", "How would you detect the shift in production?"],
    pattern: "Distribution shift",
    prerequisites: ["THEORY-001"],
    nextQuestionId: "THEORY-004",
  }),
  q({
    id: "THEORY-004", track: "math", lessonId: "ai-ml/03-experiments/regularization-is-a-tradeoff",
    kind: "prediction",
    prompt: "Validation loss rises while training loss keeps falling. Choose the intervention: more data, L2 regularization, or more epochs — and justify.",
    contextFixture: { trainLoss: "falling", valLoss: "rising" },
    expectedArtifact: "Regularization (or more data); more epochs is wrong — this is overfitting, and the gap must shrink.",
    rubric: ["Recognizes overfitting", "Rejects more epochs", "Chooses regularization or data"],
    hints: ["What does a growing train/val gap mean?", "Would more epochs widen or narrow the gap?", "Which knob fights capacity directly?"],
    pattern: "Regularization",
    prerequisites: ["THEORY-002"],
    nextQuestionId: "THEORY-005",
  }),
  q({
    id: "THEORY-005", track: "math", lessonId: "ai-ml/03-experiments/build-a-better-baseline-honestly",
    kind: "communication",
    prompt: "A team adds 10× more data but the bug class still underperforms. Explain why more data may not fix this bias, and write the finding.",
    contextFixture: { data: "10× more", minority: "bugs stay bad" },
    expectedArtifact: "A memo: the new data repeats the same 90/10 imbalance; more of the same distribution does not change the minority decision boundary.",
    rubric: ["Names imbalance persistence", "Explains why volume ≠ balance", "Proposes balancing or reweighting"],
    hints: ["What was the class ratio in the new data?", "Does 10× more of a 9:1 split change the ratio?", "What changes the boundary — volume or distribution?"],
    pattern: "Class imbalance",
    prerequisites: ["STAT-002"],
    nextQuestionId: "THEORY-006",
  }),
  q({
    id: "THEORY-006", track: "math", lessonId: "ai-ml/00-data-contract/split-the-evidence",
    kind: "transfer",
    prompt: "Design a split that respects both time and user groups: sessions arrive hourly, and the same user recurs daily.",
    contextFixture: { unit: "session", group: "user", time: "hourly" },
    expectedArtifact: "Group-by-user, then split on user's first-seen time: train = early users, test = later users, so no user appears in both.",
    rubric: ["Groups by user first", "Splits by time within groups", "States the no-user-overlap rule"],
    hints: ["If a user appears in train and test, what leaks?", "Which boundary keeps whole groups out?", "Split on group identity, not on rows."],
    pattern: "Group leakage",
    prerequisites: ["THEORY-001"],
    nextQuestionId: "DATA-001",
  }),
]
